### ISSUE TITLE
Playing media 

### ISSUE THREAD

**Issue by ryba1986** [MediaBrowser/Emby#1648]
I have an error when I want play any media:

`2016-04-14 15:33:10.1682 Error App: Error streaming media. The client has most likely disconnected or transcoding has failed.
	*** Error Report ***
	Version: 3.0.5935.0
	Command line: C:\Users\Maciej\AppData\Roaming\Emby-Server\system\MediaBrowser.ServerApplication.exe -service
	Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
	Processor count: 4
	64-Bit OS: True
	64-Bit Process: True
	Program data path: C:\Users\Maciej\AppData\Roaming\Emby-Server
	Application Path: C:\Users\Maciej\AppData\Roaming\Emby-Server\system\MediaBrowser.ServerApplication.exe
	One or more errors occurred.
	System.AggregateException
	   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at MediaBrowser.Api.Playback.Progressive.ProgressiveStreamWriter.WriteToInternal(Stream responseStream)
	InnerException: System.IO.FileNotFoundException
	Could not find file 'D:\Program Files\Emby-Server\transcoding-temp\d51f76b345471d6284f22922ad4b1b20.webm'.
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
	   at CommonIO.ManagedFileSystem.GetFileStream(String path, FileMode mode, FileAccess access, FileShare share, Boolean isAsync)
	   at MediaBrowser.Api.Playback.Progressive.ProgressiveFileCopier.<StreamFile>d__0.MoveNext()`

**Comment by LukePulverenti** [comment]
Hi, that's not actually an error. Please discuss your actual problem. Please see http://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks.
