### ISSUE TITLE
Exception thrown when attempting to get information of a media item

### ISSUE THREAD

**Issue by tidusjar** [MediaBrowser/Emby#2471]
Hi!

So i;m calling the following `/emby/users/{userId}/items/{itemId}` and i'm getting the below exception.

I'm not sure what other information i can provide. If there is something else I'd be glad to help.

Version 3.2.1.0

```
2017-02-14 21:21:12.7888 Info HttpServer: HTTP GET http://localhost:8096/emby/users/16b1dca56d554125bb7291e2588c4e63/items/459d60db6dba2568d21928b7809d710f. UserAgent: RestSharp/105.2.3.0
2017-02-14 21:21:12.7908 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.2.1.0
	Command line: C:\Users\Jamie\AppData\Roaming\Emby-Server\System\MediaBrowser.ServerApplication.exe
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	Processor count: 4
	Program data path: C:\Users\Jamie\AppData\Roaming\Emby-Server
	Application directory: C:\Users\Jamie\AppData\Roaming\Emby-Server\System
	System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
	Parameter name: item
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
	   at MediaBrowser.Api.UserLibrary.UserLibraryService.<Get>d__12.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at ServiceStack.Host.ServiceExecGeneral.<Execute>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at ServiceStack.Host.ServiceController.<Execute>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at ServiceStack.Host.RestHandler.<ProcessRequestAsync>d__19.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.<RequestHandler>d__61.MoveNext()
	---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
	Parameter name: item
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()<---
	
	System.AggregateException
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
	   at MediaBrowser.Api.UserLibrary.UserLibraryService.<Get>d__12.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at ServiceStack.Host.ServiceExecGeneral.<Execute>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at ServiceStack.Host.ServiceController.<Execute>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at ServiceStack.Host.RestHandler.<ProcessRequestAsync>d__19.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.<RequestHandler>d__61.MoveNext()
	InnerException: System.ArgumentNullException
	System.ArgumentNullException: Value cannot be null.
	Parameter name: item
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()
	
2017-02-14 21:21:12.7908 Info HttpServer: HTTP Response 500 to ::1. Time: 2ms. http://localhost:8096/emby/users/16b1dca56d554125bb7291e2588c4e63/items/459d60db6dba2568d21928b7809d710f

```

**Comment by CBers** [comment]
Luke - are you investigating this please ??

**Comment by LukePulverenti** [comment]
Is it possible you've not passed in a valid item id? This is a primitive api method that frequently. Is it possible the item could have been deleted?

**Comment by tidusjar** [comment]
Hi @LukePulverenti It doesn't matter what item id I pass it. 
I've tested it by calling `/items` then using any of those item id's and i still get the same error.


A example from a few minutes ago:

an item from `/items?parentId=GUID for Movies Folder`:

```
{
      "Name": "Ender's Game",
      "ServerId": "bc2880d526ba4c0da388ecc20f320629",
      "Id": "f65568468f1b2ce188ab18c698d4b466",
      "Container": "mp4",
      "PremiereDate": "2013-10-22T23:00:00.0000000Z",
      "CriticRating": 60,
      "ProductionLocations": [
        "United States of America"
      ],
      "OfficialRating": "GB-12",
      "CommunityRating": 6.7,
      "RunTimeTicks": 68288630784,
      "PlayAccess": "Full",
      "ProductionYear": 2013,
      "IsPlaceHolder": false,
      "IsHD": true,
      "IsFolder": false,
      "Type": "Movie",
      "LocalTrailerCount": 0,
      "VideoType": "VideoFile",
      "ImageTags": {
        "Primary": "01d27b26b6d783653ac434329f77d2b3",
        "Logo": "15dfd96ca11e0003226d6f6d7fca9e75",
        "Thumb": "791e3469d6a352990e10594e68a0c215"
      },
      "BackdropImageTags": [
        "7cda5817e7f82be362898b63fed76f1f"
      ],
      "LocationType": "FileSystem",
      "MediaType": "Video"
    },
```


Now when calling `/users/{UserId}/items/f65568468f1b2ce188ab18c698d4b466` I get that following error.

Nothing has been deleted/moves/changed in any way.

**Comment by LukePulverenti** [comment]
Can you pull up the same item in the web app detail screen and use the chrome debugger to locate the same http request. can you find the differences between your request and what the web app is doing? check the http headers as well. thanks.

**Comment by tidusjar** [comment]
That's intresting.
The call from the UI uses:
`emby/users/{UserId}/items/7f8c346f770349cfa68a1ea7e99f5dcd`
when the id for the item from `/items?parentId=GUID`
is `f65568468f1b2ce188ab18c698d4b466`

**Comment by tidusjar** [comment]
I'm going to close this for now because i've confused myself. It seems to be working now... I'll investigate and reopen if needed.

Thanks
