### ISSUE TITLE
UPnP not working in Emby, but works in other applications

### ISSUE THREAD

**Issue by OronDF343** [MediaBrowser/Emby#2499]
Emby server is not mapping the ports with UPnP even though the router supports UPnP. I verified this on the router's web UI - other applications such as qBittorrent are able to use UPnP on the network just fine.

OS: Windows 7 x64
Emby version: 3.2.5 (probably also affects also older versions)
Router: TP-Link TD-W9980 v1

**Comment by LukePulverenti** [comment]
Hi, thanks for the report. Can you please attach an Emby server log? Thanks !

**Comment by OronDF343** [comment]
Log: [server-63625878715.txt](https://github.com/MediaBrowser/Emby/files/864786/server-63625878715.txt)

I just set it up on my new PC, same as before

**Comment by LukePulverenti** [comment]
Is there still an issue with the latest release? I don't have a TP-Link router for testing but I don't see any issues with linksys. Thanks.

**Comment by OronDF343** [comment]
Still doesn't work for me

**Comment by randomevents** [comment]
Confirmed as working on a EdgeRouter Lite, Acer NightHawk and generic piece of kit from Monoprice.

**Comment by OronDF343** [comment]
@LukePulverenti Yes. I've updated to 3.2.33.0 to confirm it.

**Comment by LukePulverenti** [comment]
Why do you think you're having an issue?

**Comment by OronDF343** [comment]
I don't know much about UPnP internals, but I think either some sort of incompatibility is happening here or Emby isn't actually sending the UPnP request, since all other apps using UPnP on this network work.
I am able to find the DLNA stuff in Wireshark, but none of it makes sense to me, and I suspect I'm not looking at the right packets.

**Comment by LukePulverenti** [comment]
How are you measuring working or not working?

**Comment by OronDF343** [comment]
1) Checking if I can access Emby using my external IP, in the browser, on both HTTPS and HTTP (also tested my DuckDNS address)
2) Checking on the router's admin pages if Emby (or its port numbers) is listed in the "UPnP Settings List" (where other applications such as qBittorrent show up if they are configured correctly)

**Comment by randomevents** [comment]
Can you enable and disable the UPnP setting in advanced, restart your server and send your log. It would also be helpful if you could do the same thing, but turn off your windows firewall before the restart. Five minutes should be more than enough time. Those two logs would be helpful to look at.

**Comment by OronDF343** [comment]
Still working on the logs, but I found it in the debug log:

```
2017-10-11 08:06:27.038 Debug PortMapper: Found NAT device: uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf39::urn:schemas-upnp-org:service:WANIPConnection:1
2017-10-11 08:06:27.038 Debug PortMapper: Calling Nat.Handle on uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf39::urn:schemas-upnp-org:service:WANIPConnection:1
2017-10-11 08:06:27.040 Debug PortMapper: Found device at: http://192.168.1.2:1900/gatedesc.xml
2017-10-11 08:06:27.040 Debug PortMapper: Parsed device as: 192.168.1.2:1900
2017-10-11 08:06:27.040 Debug PortMapper: Fetching service list: 192.168.1.2:1900
2017-10-11 08:06:27.040 Debug PortMapper: NAT device found: 192.168.1.103
2017-10-11 08:06:27.043 Debug PortMapper: Creating port map on port 8096
2017-10-11 08:06:27.045 Debug PortMapper: Initiating request to: http://192.168.1.2:1900
2017-10-11 08:06:29.798 Debug HttpServer: Validating host localhost
2017-10-11 08:06:29.798 Info HttpServer: HTTP GET http://localhost:8096/emby/System/Endpoint. UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.2.0 Waterfox/55.2.0
2017-10-11 08:06:29.802 Info HttpServer: HTTP Response 200 to ::1. Time: 4ms. http://localhost:8096/emby/System/Endpoint 
2017-10-11 08:06:30.349 Info HttpClient: HttpClientManager POST: http://192.168.1.2:1900
2017-10-11 08:06:30.362 Error HttpClient: Error ProtocolError getting response from http://192.168.1.2:1900
	*** Error Report ***
	Version: 3.2.33.0
	Command line: C:\Users\Oron\AppData\Roaming\Emby-Server\System\MediaBrowser.ServerApplication.exe C:\Users\Oron\AppData\Roaming\Emby-Server\System\MediaBrowser.ServerApplication.exe
	Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 16
	Program data path: C:\Users\Oron\AppData\Roaming\Emby-Server
	Application directory: C:\Users\Oron\AppData\Roaming\Emby-Server\System
	System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
	   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
	   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
	System.Net.WebException
	   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
	   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
	
2017-10-11 08:06:30.363 Error PortMapper: Error creating port map: The remote server returned an error: (500) Internal Server Error.
```

Looks like there is an incompatibility with this particular router?

**Comment by randomevents** [comment]
can you pastebin the the xml from http://192.168.1.2:1900/gatedesc.xml ?

**Comment by OronDF343** [comment]
Have you seen my edit to my previous comment?
 Anyway, here is the XML: https://pastebin.com/ce2HbBFE

**Comment by randomevents** [comment]
What was your original setup before? What happens when you turn of Upnp on this router?

**Comment by OronDF343** [comment]
Original setup was to connect to the main router (TD-W9980 at 192.168.1.1) directly over Wi-Fi.

**Comment by LukePulverenti** [comment]
I found something that looks suspect. The url sent to the router is always the root url, missing the /upnp/xxxx sub-directories.

Looking at the code:
https://github.com/MediaBrowser/Emby/blob/dev/Mono.Nat/Upnp/UpnpNatDevice.cs#L114

controlUrl is never populated, but then it is used later to build the url, and since it is null, the entire sub-directory never becomes part of the final url.

**Comment by LukePulverenti** [comment]
Ah yes, looking at the original code this is based on, at some point along the way i ripped out an entire method that was querying the services list and filling in that info.
