### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by scrimpy** [MediaBrowser/Emby#3176]
2018-02-25 17:26:15.954 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.3.0.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.14.0.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.ObjectDisposedException: Cannot access a disposed object.
	Object name: 'SqliteItemRepository has been disposed and cannot be accessed.'.
	   at Emby.Server.Implementations.Data.BaseSqliteRepository.CheckDisposed()
	   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
	   at Emby.Server.Implementations.Playlists.PlaylistsFolder.GetEligibleChildrenForRecursiveChildren(User user)
	   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
	   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren)
	   at Emby.Server.Implementations.Playlists.PlaylistsFolder.IsVisible(User user)
	   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
	   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren)
	   at Emby.Server.Implementations.Library.UserViewManager.<GetUserViews>d__7.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at MediaBrowser.Api.UserLibrary.UserViewsService.<Get>d__5.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.<Execute>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.<ProcessRequestAsync>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.<RequestHandler>d__74.MoveNext()
	System.ObjectDisposedException
	   at Emby.Server.Implementations.Data.BaseSqliteRepository.CheckDisposed()
	   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
	   at Emby.Server.Implementations.Playlists.PlaylistsFolder.GetEligibleChildrenForRecursiveChildren(User user)
	   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
	   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren)
	   at Emby.Server.Implementations.Playlists.PlaylistsFolder.IsVisible(User user)
	   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
	   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren)
	   at Emby.Server.Implementations.Library.UserViewManager.<GetUserViews>d__7.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at MediaBrowser.Api.UserLibrary.UserViewsService.<Get>d__5.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.<Execute>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.<ProcessRequestAsync>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.<RequestHandler>d__74.MoveNext()

**Comment by scrimpy** [comment]
Web interface is not loading anymore.
