### ISSUE TITLE
MissingMethodException: IProviderManager.SaveMetadata(BaseItem, ItemUpdateType)

### ISSUE THREAD

**Issue by coldacid** [MediaBrowser/Emby#3188]
This method has been missing since 3.2.70 in the Windows x64 builds but continues to be present in the MediaBrowser.Controller.dll in the MediaBrowser.Server.Core NuGet package (3.3.29 at time of writing, released 2018 Feb 28). This breaks a personal plugin of mine which relies on this method.

```
2018-03-04 14:21:22.615 Error TaskManager: Error
	*** Error Report ***
	Version: 3.3.1.0
	Command line: C:\Users\Chris\AppData\Roaming\MediaBrowser-Server\system\EmbyServer.dll -service
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 4
	Program data path: C:\Users\Chris\AppData\Roaming\MediaBrowser-Server
	Application directory: C:\Users\Chris\AppData\Roaming\MediaBrowser-Server\system
	System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Providers.IProviderManager.SaveMetadata(MediaBrowser.Controller.Entities.IHasMetadata, MediaBrowser.Controller.Library.ItemUpdateType)'.
	   at MediaBrowser.Plugins.MetadataSaver.SaveMetadataScheduledTask.Operation.StackExecute(BaseItem item)
	   at MediaBrowser.Plugins.MetadataSaver.SaveMetadataScheduledTask.Operation.Execute()
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.<ExecuteInternal>d__68.MoveNext()
	System.MissingMethodException
	   at MediaBrowser.Plugins.MetadataSaver.SaveMetadataScheduledTask.Operation.StackExecute(BaseItem item)
	   at MediaBrowser.Plugins.MetadataSaver.SaveMetadataScheduledTask.Operation.Execute()
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.<ExecuteInternal>d__68.MoveNext()
```

**Comment by LukePulverenti** [comment]
Strange that doesn't sound right. What runtime is the plugin project targeting?

**Comment by coldacid** [comment]
The plugin project is targeting netstandard1.3.

**Comment by LukePulverenti** [comment]
Oh wait I see from here, the IHasMetadata interface is gone. If you pull the latest nuget then you should be fine. It sounds like you haven't actually updated that.

**Comment by coldacid** [comment]
I did, though. Latest package is 3.3.29 and I was able to rebuild successfully without code changes with it.

**Comment by LukePulverenti** [comment]
I don't have an answer for you then, because that code appears to be compiled against an older nuget version. In fact, other plugins performing the same operations were able to be updated for the newer server  by updating nuget.

**Comment by coldacid** [comment]
Okay, looks like I had a silent failure moving the rebuild into the plugins directory. My bad.

**Comment by LukePulverenti** [comment]
Glad you sorted it out, thanks !
