### ISSUE TITLE
musicbrainz issue with quotes, Albumname = 12"Mixes

### ISSUE THREAD

**Issue by quickmic** [MediaBrowser/Emby#3271]
.net core 3.4.1.3 beta

`2018-05-13 10:12:10.694 Info HttpClient: GET http://musicbrainz01.eastus2.cloudapp.azure.com:8080/ws/2/release/?query="12%22+Mixes" AND arid:5f4b4a0e-3888-45e8-80e8-fab00dda4870
2018-05-13 10:12:10.817 Error App: Error in MusicBrainz
	*** Error Report ***
	Version: 3.4.1.3
	Command line: /opt/emby/EmbyServer.dll
	Operating system: Unix 4.15.17.1
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 12
	Program data path: /opt/programdata
	Application directory: /opt/emby
	MediaBrowser.Model.Net.HttpException: BadRequest
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, Boolean isSearch, Boolean forceMusicBrainzProper, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResult(String albumName, String artistId, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	MediaBrowser.Model.Net.HttpException
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, Boolean isSearch, Boolean forceMusicBrainzProper, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResult(String albumName, String artistId, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	
`

**Comment by LukePulverenti** [comment]
It's resolved for the next release, thanks.

**Comment by quickmic** [comment]
:)
