### ISSUE TITLE
Error sending socket message 

### ISSUE THREAD

**Issue by ArthurAttout** [MediaBrowser/Emby#3306]
When watching a video from the Android App, the video sometimes hangs, and the only way to keep going is to restart the app.

This is what shows up in the server logs : 

```
2018-06-02 17:12:05.797 Error Dlna: Error sending socket message from 0.0.0.0 to 169.254.10.1:57999
	*** Error Report ***
	Version: 3.4.1.0
	Command line: C:\Users\Le Roi Arthur\AppData\Roaming\Emby-Server\system\EmbyServer.dll
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 4
	Program data path: C:\Users\Le Roi Arthur\AppData\Roaming\Emby-Server\programdata
	Application directory: C:\Users\Le Roi Arthur\AppData\Roaming\Emby-Server\system
	System.Net.Sockets.SocketException (0x80004005): A socket operation was attempted to an unreachable network 
	   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
	   at System.Net.Sockets.Socket.EndSendTo(IAsyncResult asyncResult)
	   at Emby.Server.Implementations.Net.UdpSocket.<>c__DisplayClass22_0.<SendToAsync>b__0(IAsyncResult callbackResult)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Rssdp.Infrastructure.SsdpCommunicationsServer.<SendFromSocket>d__24.MoveNext()
	System.Net.Sockets.SocketException
	   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
	   at System.Net.Sockets.Socket.EndSendTo(IAsyncResult asyncResult)
	   at Emby.Server.Implementations.Net.UdpSocket.<>c__DisplayClass22_0.<SendToAsync>b__0(IAsyncResult callbackResult)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Rssdp.Infrastructure.SsdpCommunicationsServer.<SendFromSocket>d__24.MoveNext()
```

Android app version : 2.9.92 (Android 7.0)
Server version : 3.4.1.0 (Windows)

**Comment by LukePulverenti** [comment]
Resolved for next release of the app and server, thanks.

**Comment by ArthurAttout** [comment]
Wow, that was quick .. Thanks !
