### ISSUE TITLE
  I realized the IIsoMounter interface, but I did not mount ISO files while playing.

### ISSUE THREAD

**Issue by juebanlin** [MediaBrowser/Emby#3368]
code:
```
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using MediaBrowser.Model.Diagnostics;
using MediaBrowser.Model.IO;
using MediaBrowser.Model.Logging;
using MediaBrowser.Model.System;
using System.Collections.Generic;

namespace WinIsoMounter
{
    public class WindowsMounter : IIsoMounter
    {
        #region Private Fields

        private readonly ILogger Logger;
        private readonly IEnvironmentInfo EnvironmentInfo;
        private readonly IIsoManager IsoManager;
        private readonly IFileSystem FileSystem;
        private readonly IProcessFactory ProcessFactory;

        #endregion

        #region Constructor(s)

        public WindowsMounter(ILogger logger, IEnvironmentInfo environment, IIsoManager isoManager,IProcessFactory processFactory, IFileSystem fileSystem )
        {
            Logger = logger;
            EnvironmentInfo = environment;
            IsoManager = isoManager;
            FileSystem = fileSystem;
            ProcessFactory = processFactory;
            Logger.Debug("WindowsIsoMounter init start");
            if (environment != null)
            {
                Logger.Debug("environment is StackTrace:" + environment.StackTrace);
            }
            if (isoManager != null)
            {
                /**
                 * 
                */
                List<IIsoMounter> list = new List<IIsoMounter>();
                list.Add(this);
                isoManager.AddParts(list);
                Logger.Debug("isoManager init:");
            }
            Logger.Debug("WindowsIsoMounter inited");
        }

        #endregion

        #region Interface Implementation for IIsoMounter

        public string Name
        {
            get { return "WindowsIsonMounter"; }
        }

        /// <summary>
        /// 是否能挂载此文件
        /// </summary>
        /// <param name="path"></param>
        /// <returns></returns>
        public bool CanMount(string path)
        {
            Logger.Debug("is canMount isoPath:"+ path);
            if (EnvironmentInfo.OperatingSystem != MediaBrowser.Model.System.OperatingSystem.Windows)
            {
                return false;
            }
            bool isIsoPath = string.Equals(Path.GetExtension(path), ".iso", StringComparison.OrdinalIgnoreCase);
            if (!isIsoPath)
            {
                Logger.Debug("is not isoPath:[{1}]", path);
                return false;
            }
            return true;
        }
```
### CanMount method does not have log output. How did it not be called?
server log:

2018-07-18 11:01:42.249 Debug App:  isoManager init:
2018-07-18_ 11:01:42.249 Debug App: WindowsIsoMounter inited
……
2018-07-18 11:07:48.139 Debug App: Running FFProbeProvider for D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso
2018-07-18 11:07:48.142 Debug App: Running MovieNfoProvider for D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso
2018-07-18 11:07:48.150 Debug App: MovieNfoProvider returned no metadata for D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso
2018-07-18 11:07:48.160 Debug App: Running MovieDbProvider for D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso
2018-07-18 11:07:48.259 Info HttpClient: GET https://api.themoviedb.org/3/configuration?api_key=f6bd687ffa63cd282b6ff2c6877f2669
2018-07-18 11:07:48.640 Info HttpServer: HTTP GET http://home.jueb.net:8096/favicon.ico. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
2018-07-18 11:07:48.641 Debug HttpResultFactory: Transmit file C:\Users\admin\AppData\Roaming\Emby-Server\system\dashboard-ui\favicon.ico
2018-07-18 11:07:48.642 Info HttpServer: HTTP Response 200 to 118.122.119.18. Time: 2ms. http://home.jueb.net:8096/favicon.ico 
2018-07-18 11:07:59.319 Error HttpClient: Error getting response from https://api.themoviedb.org/3/configuration?api_key=f6bd687ffa63cd282b6ff2c6877f2669
	*** Error Report ***
	Version: 3.5.0.0
	Command line: C:\Users\admin\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 16
	Program data path: C:\Users\admin\AppData\Roaming\Emby-Server\programdata
	Application directory: C:\Users\admin\AppData\Roaming\Emby-Server\system
	System.Net.Http.HttpRequestException: 涓嶇煡閬撹繖鏍风殑涓绘満銆� ---> System.Net.Sockets.SocketException: 涓嶇煡閬撹繖鏍风殑涓绘満銆�
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	System.Net.Http.HttpRequestException
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
	   at System.Threading.Tasks.ValueTask`1.get_Result()
	   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	InnerException: System.Net.Sockets.SocketException
	System.Net.Sockets.SocketException (11001): 涓嶇煡閬撹繖鏍风殑涓绘満銆�
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	
2018-07-18 11:07:59.334 Error App: Error in TheMovieDb
	*** Error Report ***
	Version: 3.5.0.0
	Command line: C:\Users\admin\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 16
	Program data path: C:\Users\admin\AppData\Roaming\Emby-Server\programdata
	Application directory: C:\Users\admin\AppData\Roaming\Emby-Server\system
	System.Net.Http.HttpRequestException: 涓嶇煡閬撹繖鏍风殑涓绘満銆� ---> System.Net.Sockets.SocketException: 涓嶇煡閬撹繖鏍风殑涓绘満銆�
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MediaBrowser.Providers.Movies.MovieDbProvider.GetMovieDbResponse(HttpRequestOptions options)
	   at MediaBrowser.Providers.Movies.MovieDbProvider.GetTmdbSettings(CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	System.Net.Http.HttpRequestException
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MediaBrowser.Providers.Movies.MovieDbProvider.GetMovieDbResponse(HttpRequestOptions options)
	   at MediaBrowser.Providers.Movies.MovieDbProvider.GetTmdbSettings(CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	InnerException: System.Net.Sockets.SocketException
	System.Net.Sockets.SocketException (11001): 涓嶇煡閬撹繖鏍风殑涓绘満銆�
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	
2018-07-18 11:07:59.494 Info App: User policy for admin. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2018-07-18 11:07:59.525 Info App: Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 18625277
2018-07-18 11:07:59.526 Info App: Profile: Unknown Profile, Path: D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso, isEligibleForDirectPlay: True, isEligibleForDirectStream: False
2018-07-18 11:07:59.549 Info App: Profile: Unknown Profile, No direct play profiles found for Path: D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso
2018-07-18 11:07:59.631 Info App: RemoteClientBitrateLimit: 20000000, RemoteIp: 110.184.155.162, IsInLocalNetwork: False
2018-07-18 11:07:59.631 Info App: Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 18625277
2018-07-18 11:07:59.631 Info App: Profile: Unknown Profile, Path: D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso, isEligibleForDirectPlay: True, isEligibleForDirectStream: False
2018-07-18 11:07:59.631 Info App: Profile: Unknown Profile, No direct play profiles found for Path: D:\test\Suicide Squad Hell to Pay 2018 Blu-ray 1080p AVC DTS-HD MA 5.1-Blues@OurBits.iso
2018-07-18 11:07:59.679 Info App: RemoteClientBitrateLimit: 20000000, RemoteIp: 110.184.155.162, IsInLocalNetwork: False

**Comment by LukePulverenti** [comment]
You'll need to build a plugin by following our plugin building guide:
https://github.com/MediaBrowser/Emby/wiki/How-to-build-a-Server-Plugin
And put this class into the plugin.

**Comment by juebanlin** [comment]
I refer to Emby.IsoMounting and modify and add my own implementation, and I also have output in the log, and I can see my plug-in in emby plugin list. @LukePulverenti

**Comment by LukePulverenti** [comment]
Got it ok. Then try playing it in the web app.

**Comment by juebanlin** [comment]
The problem is, based on my log analysis, I found that there was no way to call canMount at all. It is more impossible to execute the Mount method. @LukePulverenti

**Comment by LukePulverenti** [comment]
You dont' call it. It calls you.

**Comment by juebanlin** [comment]
Is there any change in the method in IsoManager? But I see that it does call the canMount method.
[ Emby/Emby.Server.Implementations/IO/IsoManager.cs ](url)
