### ISSUE TITLE
SubtitleManager, crashing and timeouts

### ISSUE THREAD

**Issue by BloodyIron** [MediaBrowser/Emby#3444]
* Ubuntu 18.04
* Emby 3.5.3.0

Whenever I try to download missing subtitles, I get a boatload of these in the logs (name resolution works in the system btw):

`
2018-10-01 16:50:42.358 Error SubtitleManager: Error downloading subtitles from Open Subtitles
	*** Error Report ***
	Version: 3.5.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.34
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	MediaBrowser.Model.Net.HttpException: Cancelling connection to https://api.opensubtitles.org/xml-rpc due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
	   at OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
	MediaBrowser.Model.Net.HttpException
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
	   at OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
`

Not sure how to correct this, bug perhaps?

**Comment by BloodyIron** [comment]
BTW a bunch of requests do get HTTP 200 code, but most of them seem to timeout.

**Comment by LukePulverenti** [comment]
It's contacting an external provider. Every once in a while, some of those requests may time out. You can always just disable the feature if you don't want to see these in your log.

**Comment by BloodyIron** [comment]
@LukePulverenti the issue is subtitle scanning is taking upwards of like 10min-30min+. I believe these issues are related to why it takes so long. All other tasks typically take seconds to complete.

**Comment by LukePulverenti** [comment]
That's because timeouts are going to result in delays. My suggestion is just have it run in the middle of the night and then you can just set it and forget it without having to care how long it takes.

**Comment by BloodyIron** [comment]
Why is it trying to re-download subtitles for media that already has them downloaded? That's what it looks like it's doing though.

**Comment by LukePulverenti** [comment]
It depends on how you've configured the downloading.
