### ISSUE TITLE
【Connect Failed】Emby Server in MacOS，iphone cannot connect

### ISSUE THREAD

**Issue by HyWell** [MediaBrowser/Emby#3456]
Successfully accessing Emby Server IP using Safari on iPhone, but failed to connect using Emby App。
Emby Server Version：3.5.3.0
MacOS Mojave 10.14
iPhone：12.0.1
![img_4622](https://user-images.githubusercontent.com/21263451/47191966-b58b2280-d37c-11e8-9ce1-82c7c4338590.png)
![img_4624](https://user-images.githubusercontent.com/21263451/47192021-000c9f00-d37d-11e8-88c2-e6ffaa60883a.png)
How do I need to deal with it？

**Comment by szakes1** [comment]
@HyWell Not everyone knows Mandarin, so please post the error message in English, please.

**Comment by HyWell** [comment]
https://emby.media/community/index.php?/topic/62875-unable-to-connect-from-app-to-server/
like this

**Comment by HyWell** [comment]
> @HyWell Not everyone knows Mandarin, so please post the error message in English, please.
Log files display error messages
``2018-11-05 09:42:16.842 Info HttpServer: HTTP POST http://192.168.100.31:8096/emby/Users/authenticatebyname. UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B92
2018-11-05 09:42:16.844 Info UserManager: Authentication request for hywell has succeeded.
2018-11-05 09:42:16.845 Info SessionManager: Creating new access token for user XXXXXXXX
2018-11-05 09:42:16.849 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.3.0
	Command line: /Applications/EmbyServer.app/Contents/MacOS/EmbyServer.dll
	Operating system: Unix 18.0.0.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /Users/hywell/.config/emby-server
	Application directory: /Applications/EmbyServer.app/Contents/MacOS
	Constraint: NOT NULL constraint failed: Tokens.DeviceName
	SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
	   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
	   at SQLitePCL.pretty.StatementImpl.MoveNext()
	   at Emby.Server.Implementations.Security.AuthenticationRepository.<>c__DisplayClass5_0.<Create>b__0(IDatabaseConnection db)
	   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
	   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
	   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
	   at Emby.Server.Implementations.Security.AuthenticationRepository.Create(AuthenticationInfo info)
	   at Emby.Server.Implementations.Session.SessionManager.GetAuthorizationToken(User user, String deviceId, String app, String appVersion, String deviceName)
	   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
	   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	SQLitePCL.pretty.SQLiteException
	   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
	   at SQLitePCL.pretty.StatementImpl.MoveNext()
	   at Emby.Server.Implementations.Security.AuthenticationRepository.<>c__DisplayClass5_0.<Create>b__0(IDatabaseConnection db)
	   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
	   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
	   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
	   at Emby.Server.Implementations.Security.AuthenticationRepository.Create(AuthenticationInfo info)
	   at Emby.Server.Implementations.Session.SessionManager.GetAuthorizationToken(User user, String deviceId, String app, String appVersion, String deviceName)
	   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
	   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	
2018-11-05 09:42:16.849 Info HttpServer: HTTP Response 500 to 192.168.100.42. Time: 6ms. http://192.168.100.31:8096/emby/Users/authenticatebyname ``

**Comment by LukePulverenti** [comment]
Are you still having a problem with this? thanks.

**Comment by LukePulverenti** [comment]
Closing due to inactivity, but please feel free to re-open with the requested information. Thanks !

**Comment by HyWell** [comment]
The problem is still
