### ISSUE TITLE
User account login issue

### ISSUE THREAD

**Issue by danashurst** [MediaBrowser/Emby#3481]
Im having an issue logging in to my Emby account on my local server. I attached this account to an Emby Connect account whilst playing around with Amazon Alexa. For one reason or another I couldnt get it to work (I think it requires a secure connection that I have not yet configured). I therefore unlinked my account from connect and was unable to log in. I tried resetting the password on the server admin interface for the account, and still get the same error.

**Steps to reproduce:**
- Create an account
- Connect account with Emby Connect
- Remove Emby Connect Username via admin interface
- Login fails.

Would be great to see a fix for this. In the interim, is there a way to copy account data - specifically watched items to another account? I created a brand new local account, and login is successful.

**Comment by danashurst** [comment]
Log file yeilds:

2018-11-22 22:18:47.850 Info HttpServer: HTTP POST http://*********/emby/Users/authenticatebyname. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
2018-11-22 22:18:47.851 Error UserManager: Error authenticating with provider Default
	*** Error Report ***
	Version: 3.5.3.0
	Command line: C:\Users\*********\AppData\Roaming\Emby-Server\system\EmbyServer.dll
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 12
	Program data path: C:\Users\*********\AppData\Roaming\Emby-Server\programdata
	Application directory: C:\Users\*********\AppData\Roaming\Emby-Server\system
	System.Exception: Invalid username or password
	   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
	   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
	System.Exception
	   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
	   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
	
2018-11-22 22:18:47.851 Info HttpClient: POST https://connect.emby.media/service/user/authenticate
2018-11-22 22:18:48.272 Error HttpServer: Forbidden.
2018-11-22 22:18:48.272 Info HttpServer: HTTP Response 401 to 86.6.29.117. Time: 422ms. http://*********/emby/Users/authenticatebyname

**Comment by LukePulverenti** [comment]
Hi, what user are you trying to login with? The local server credentials, or your Emby Connect user?

**Comment by danashurst** [comment]
The user was a local user, that was converted to a connect user, then the email address was removed and should have become a local user again.

**Comment by LukePulverenti** [comment]
Hi, this should no longer be an issue, but if you are still having one then please feel free to re-open and we'll be happy to help. Thanks.
