### ISSUE TITLE
Unable to scrub video 

### ISSUE THREAD

**Issue by tulipszs** [MediaBrowser/Emby#3501]
Hi, 

I am unable to seek into a video using the web player (Mozilla Firefox 64.0). The video playback is perfectly fine until I touch the timeline. 

I found this in the logs: 
`
2018-12-31 12:01:31.206 Info App: Stopping ffmpeg process with q command for /var/lib/emby/transcoding-temp/81c8e1cb1e50dd62defffc1ac090037f.m3u8
2018-12-31 12:01:31.287 Info App: FFMpeg exited with code 0
2018-12-31 12:01:31.296 Info App: /usr/bin/ffmpeg -ss 00:19:30.000 -noaccurate_seek -f matroska,webm -i file:"/var/Media/Movies/Django Unchained (2012).mkv" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 384000 -af "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 6 -segment_time_delta -1170 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 195 -segment_list "/var/lib/emby/transcoding-temp/81c8e1cb1e50dd62defffc1ac090037f.m3u8" -y "/var/lib/emby/transcoding-temp/81c8e1cb1e50dd62defffc1ac090037f%d.ts"
2018-12-31 12:01:31.586 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.3.0
	Command line: /usr/lib/emby-server/EmbyServer.dll -programdata /var/lib/emby -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.14.90.1
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /usr/lib/emby-server
	System.Exception: Error starting ffmpeg
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String segmentId)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	System.Exception
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String segmentId)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
`

For readability I've also put it on pastebin: https://pastebin.com/raw/4HwvZfD2

![2018-12-31-120619_1365x668_scrot](https://user-images.githubusercontent.com/22307502/50564667-d8c73c00-0cf4-11e9-8aed-3bbec0d31da0.png)
![2018-12-31-120725_1365x667_scrot](https://user-images.githubusercontent.com/22307502/50564668-debd1d00-0cf4-11e9-8a94-166a2f4b0132.png)

I am running Arch with their distribution 4.14.90-1-lts kernel. I have my media folder in /var/Media/. Each file is symlinked to the video file which is in my home directory. Emby (temporarily) is running as root until I fix the whole binding to port 80/443 issue. 

Any other information needed I can provide, Thanks!

**Comment by LukePulverenti** [comment]
Hi, you'll need to roll back your system installed ffmpeg to 4.0.2. 4.1 is not yet supported. Thanks.
