### ISSUE TITLE
TMDBID is set to zero

### ISSUE THREAD

**Issue by benkap** [MediaBrowser/Emby#3504]
Hi!

I am running 3.5.3.0 server on linux lite.
I noticed that a lot of my Movies (I have about 600 and about 300 of them has this issue) are set in the NFO file with
```
<tmdbid>0</tmdbid>
```

I can't remove this from the NFO or from MetaData editor since:
1. Each Scan of the Movie Library return all this zero ID back to the same movies.
2. I can lock 300 manually Movies in the Metadata Manager but this happen to new movies which are added.

The issue is that each scan of the Movie Library makes a lot of HTTP request getting an error since there is no ID zero which load the disk IO (to write the exceptions logs) and consume unneeded traffic under the TMDB API key.

This is the error from emby-server log:

```
2019-01-07 01:13:58.420 Error App: Error in TheMovieDb
	*** Error Report ***
	Version: 3.5.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.43
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/emby/cache/tmdb-movies2/0/all-en.json'.
	   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
	   at Emby.Common.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	System.IO.DirectoryNotFoundException
	   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
	   at Emby.Common.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Movies.GenericMovieDbInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

Which repeat for each movie (maybe even multiple time - the logs are full of those exceptions.
Not sure what other impact this may have on the Library if any.

Thanks,
Ben

**Comment by LukePulverenti** [comment]
Hi, if you were to add a new movie, would this happen?

**Comment by benkap** [comment]
Hi, I don't know what is the logic behind it since i have old movies which this issue doesn't happen (TMDB ID is empty or with a valid ID) and i have recently added movies (past 2-3 weeks) which has '0' (Zero) in the TMDB ID section (and NFO) and vice versa (old with zero and new with empty/valid id).

So the answer is yes new added movies get's TMDB ID zero but not all of them, and i don't know on what condition this happen.

**Comment by LukePulverenti** [comment]
When you add a new movie, does it include a pre-existing nfo that emby reads?

**Comment by benkap** [comment]
That's integrating havn't thought about it.. It's possible since i had other app for metadata...

__I now did the following:__

1. On the newest movie I have added: I've check the movie directory - All files where owned by **emby** user and group except the ```.mkv``` and ```.nfo``` which where owned by **root** user. But this movie did not have this problem, It had a tmdb ID (as opposed to empty/zero ID where other providers ID are found). So that's not a good movie example but looks like you are right that other apps may add the ```.nfo``` data...
2. I've located the next newest movie added that DID had ```<tmdbid>0</tmdbid>``` in it's NFO file (The movie added Jan  4 "Jarhead (2005)"). This time all files in the movie directory were owned by ```emby``` user and group (including ```.mkv``` and ```.nfo``` files).
3. I've deleted the NFO file and immediately refreshed metadata from the UI with **replace all metadata** option on this movie. 
4. In the new NFO file (verified by 'create time') there was still  ```<tmdbid>0</tmdbid>``` section in it. 

I hope that's help. Let me know if i can add more information.

**Comment by LukePulverenti** [comment]
Deleting the nfo will not delete information from the database. Instead of doing that, try using Identify feature.

**Comment by benkap** [comment]
Ok I identify manually 160 items (took a while) and confirmed that the issue cannot reproduce. I suspect (like you suggested) that this happened due to a combination of 1. Another app adding NFO files and 2. Filesystem level permissions that denied emby user access.

Thanks!
