### ISSUE TITLE
Auto-Organize not working (using aniDB each time)

### ISSUE THREAD

**Issue by poulpito** [MediaBrowser/Emby#3510]
Hi :) 

Since update in 4.0.0.2 (windows server) 
the auto organize function is not working anymore. 
when i try to manually seach for a tv or movie  i get a Null picture 
![firefox_ohhcd8bmqi](https://user-images.githubusercontent.com/4135866/51444498-9ba10900-1cf8-11e9-8b48-24cebb2f5612.png)

i when i check in log : 

> 2019-01-20 21:09:23.372 Error ProviderManager: Error searching
> 	*** Error Report ***
> 	Version: 4.0.0.2
> 	Command line: C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll
> 	Operating system: Microsoft Windows NT 6.2.9200.0
> 	64-Bit OS: True
> 	64-Bit Process: True
> 	User Interactive: True
> 	Processor count: 16
> 	Program data path: C:\Users\Administrator\AppData\Roaming\Emby-Server
> 	Application directory: C:\Users\Administrator\AppData\Roaming\Emby-Server\system
> 	System.MissingMethodException: System.MissingMethodException: Method not found: 'System.Nullable`1<System.DateTime> MediaBrowser.Controller.Entities.BaseItem.get_PremiereDate()'.
> 	   at MediaBrowser.Plugins.Anime.Providers.AniDB.Metadata.AniDbEpisodeProvider.GetSearchResults(EpisodeInfo searchInfo, CancellationToken cancellationToken)
> 	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
> 	   at MediaBrowser.Plugins.Anime.Providers.AniDB.Metadata.AniDbEpisodeProvider.GetSearchResults(EpisodeInfo searchInfo, CancellationToken cancellationToken)
> 	   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
> 	   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
> 	Source: MediaBrowser.Plugins.Anime

seems it call for the aniDB plugin  except that this was never check into media library options (only tvdb)

if i manually try to attach a tv episode to an existing serie, i found the same type of line in log. 
it's still trying to find meta with anidb

starting the server, i've found thoses error :
```
SimpleInjector.ActivationException: SimpleInjector.ActivationException: No registration for type Plugin could be found and an implicit registration could not be made. One or more errors occurred. (There is an error in XML document (3797, 69).) ---> System.AggregateException: One or more errors occurred. (There is an error in XML document (3797, 69).) ---> System.InvalidOperationException: There is an error in XML document (3797, 69). ---> System.OverflowException: Value was either too large or too small for a signed byte.
	   at System.SByte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read2_AnimelistMapping(Boolean isNullable, Boolean checkType)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read7_AnimelistAnime(Boolean isNullable, Boolean checkType)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read8_Animelist(Boolean isNullable, Boolean checkType)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read9_animelist()
	   --- End of inner exception stack trace ---
	   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
	   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
	   at AnimeLists.Downloader.Download()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at MediaBrowser.Plugins.Anime.Providers.AniDB.Converter.AnidbConverter..ctor(IApplicationPaths paths)
	   at MediaBrowser.Plugins.Anime.Plugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger logger)
	   at lambda_method(Closure )
	   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
	   at SimpleInjector.InstanceProducer.GetInstance()
	   --- End of inner exception stack trace ---
	   at SimpleInjector.InstanceProducer.GetInstance()
	   at SimpleInjector.Container.GetInstance(Type serviceType)
	   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Tuple`2 typeInfo)
	Source: SimpleInjector
	TargetSite: System.Object GetInstance()
	   at SimpleInjector.InstanceProducer.GetInstance()
	   at SimpleInjector.Container.GetInstance(Type serviceType)
	   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Tuple`2 typeInfo)
	InnerException: System.AggregateException: One or more errors occurred. (There is an error in XML document (3797, 69).)
	Source: System.Private.CoreLib
	TargetSite: TResult GetResultCore(Boolean)
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at MediaBrowser.Plugins.Anime.Providers.AniDB.Converter.AnidbConverter..ctor(IApplicationPaths paths)
	   at MediaBrowser.Plugins.Anime.Plugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger logger)
	   at lambda_method(Closure )
	   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
	   at SimpleInjector.InstanceProducer.GetInstance()
	InnerException: System.InvalidOperationException: There is an error in XML document (3797, 69).
	Source: System.Private.Xml
	TargetSite: System.Object Deserialize(System.Xml.XmlReader, System.String, System.Xml.Serialization.XmlDeserializationEvents)
	   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
	   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
	   at AnimeLists.Downloader.Download()
	InnerException: System.OverflowException: Value was either too large or too small for a signed byte.
	Source: System.Private.CoreLib
	TargetSite: SByte Parse(System.ReadOnlySpan`1[System.Char], System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
	   at System.SByte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read2_AnimelistMapping(Boolean isNullable, Boolean checkType)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read7_AnimelistAnime(Boolean isNullable, Boolean checkType)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read8_Animelist(Boolean isNullable, Boolean checkType)
	   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimelist.Read9_animelist()
```

my guess is that if the plugin is not properly registered it could cause that ? 

Please advice about what i can try :) 
(VM is using snapshot so i can debug by reinstalling emby over the existing if needed but i'd like to be sure before trying to play)

**Comment by LukePulverenti** [comment]
Hi, try updating the anime plugin.

**Comment by poulpito** [comment]
Hi @LukePulverenti 

i've try to update  and after   uninstall / reintall   with same behaviour 
(no more errors on emby restart about missing xml) 

here are latest log
[error.log](https://github.com/MediaBrowser/Emby/files/2782823/error.log)

**Comment by LukePulverenti** [comment]
Ok unfortunately you'll need to remove the anime plugin or not use auto-organize for now. The anime plugin is a community maintained plugin and I just don't know enough about it to be able to give you a better answer. Thanks.

**Comment by LukePulverenti** [comment]
Closing as this is plugin related. Thanks.
