### ISSUE TITLE
EMBY crashes at the same time of the hour. 4.1.0.1 beta

### ISSUE THREAD

**Issue by travman19** [MediaBrowser/Emby#3512]
Faulting application name: EmbyServer.exe, version: 0.0.0.0, time stamp: 0x5bca0f4b
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19178, time stamp: 0x5bc006fd
Exception code: 0xe0434352
Fault offset: 0x0000000000008e6c
Faulting process id: 0x1344
Faulting application start time: 0x01d4b1dc565a0bd4
Faulting application path: C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 97d81c55-1dcf-11e9-80c8-000c29820593
Faulting package full name: 
Faulting package-relative application ID: 

____________________________________________________________________________________________________

Application: EmbyServer.exe
CoreCLR Version: 4.6.27019.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (The process cannot access the file 'C:\Users\Administrator\AppData\Roaming\Emby-Server\programdata\logs\embyserver-1.txt' because it is being used by another process.) ---> System.IO.IOException: The process cannot access the file 'C:\Users\Administrator\AppData\Roaming\Emby-Server\programdata\logs\embyserver-1.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Emby.Server.Implementations.Logging.FileLogger..ctor(String path)
   at Emby.Server.Implementations.Logging.SimpleLogManager.ReloadLogger(LogSeverity severity, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at EmbyServer.Program.Main(String[] args)

**Comment by LukePulverenti** [comment]
Please let me know if this is resolved in 4.1.0.2. Thanks !

**Comment by travman19** [comment]
I am on 4.1.0.2 and it occurred again last night.

Please let me know what you need from me

**Comment by LukePulverenti** [comment]
Please attach a new log file. Thanks.

**Comment by LukePulverenti** [comment]
Hi there, are you still seeing this?

**Comment by LukePulverenti** [comment]
Closing due to abandonment, but please feel free to re-open with the requested information. Thanks.
