### ISSUE TITLE
Seek appears to be broken in the web app for Emby Version 4.0.1.0

### ISSUE THREAD

**Issue by Aterfax** [MediaBrowser/Emby#3517]
I recently updated to Version 4.0.1.0 and am now unable to resume files or to seek files in the web app.

Attempting to do so results in the file stopping (or never starting) in current versions of Firefox, Chrome and Edge with the following console output:

```appRouter - processing path request /web#!/videoosd.html router.js:1:5206
appRouter - user is authenticated router.js:1:5727
appRouter - proceeding to /web#!/videoosd.html router.js:1:6114
Active player: {"name":"Html Video Player","id":"htmlvideoplayer","playerName":"Html Video Player","playableMediaTypes":[false,true,false,false,false],"isLocalPlayer":true,"supportedCommands":["GoHome","GoToSettings","VolumeUp","VolumeDown","Mute","Unmute","ToggleMute","SetVolume","SetAudioStreamIndex","SetSubtitleStreamIndex","SetMaxStreamingBitrate","DisplayContent","GoToSearch","DisplayMessage","SetRepeatMode","PlayMediaSource","PlayTrailers","ToggleFullscreen","SetBrightness"]} playbackmanager.js:1:15568
Requesting url without automatic networking: https://website:8097/emby/Sessions/Playing apiclient.js:1:12885
nowplaying event: playbackstart videoosd.js:1:12781
Setting new text track index to: 2 plugin.js:1:17005
HLS Error: Type: networkError Details: fragLoadError Fatal: false htmlmediahelper.js:1:4244
hls.js response error code: 500 htmlmediahelper.js:1:4461
Requesting url without automatic networking: https://website:8097/emby/Sessions/Playing/Progress
apiclient.js:1:12885
AbortError: The operation was aborted. 
```

This does not appear to be caused by any specific file type and also seek does not work with transcoding or direct playback.

*Using the Docker!

**Comment by Aterfax** [comment]
Might be related to audio stream?

Works on this file:

![image](https://user-images.githubusercontent.com/8648058/51648400-53901980-1f78-11e9-8901-7242a0e5461a.png)
 And this file:

![image](https://user-images.githubusercontent.com/8648058/51648453-85a17b80-1f78-11e9-859e-431a640da5e4.png)


Does not work on this file:

![image](https://user-images.githubusercontent.com/8648058/51648491-a79afe00-1f78-11e9-84cf-43f10f8aa8b3.png)

or this file:

![image](https://user-images.githubusercontent.com/8648058/51648580-ea5cd600-1f78-11e9-9983-bec0a87112e4.png)

Nor this file:

![image](https://user-images.githubusercontent.com/8648058/51648638-2c861780-1f79-11e9-9cce-6c3d2f612ccb.png)


This appears to be related to the AC3 audio codec?

**Comment by LukePulverenti** [comment]
Hi there, can you please attach the emby server and ffmpeg logs? Thanks !

**Comment by Aterfax** [comment]
Will do if there's a handy way to anonymise the user data?

**Comment by Aterfax** [comment]
Emby seems to be computing a negative time to seek to resulting in an encoder error?

Excerpt from embyserver.txt

```
2019-01-24 10:36:56.967 Info App: FFMpeg exited with code 0
2019-01-24 10:36:56.994 Info App: ProcessRun 'StreamTranscode 6237a7' Execute: /usr/bin/ffmpeg -ss 00:20:54.000  -noaccurate_seek -f matroska -i file:"/media/Media/TV Shows/folder/file.mkv" -threads 0 -map 0:0 -map 0:1 -map -0:s -c:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 aac -strict experimental -disposition:a:0 default -ac:a:0 2 -ab:a:0 128000 -af:a:0 "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 6 -segment_time_delta -1254 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 209 -segment_list "/config/transcoding-temp/42b04b6503f3de8e99f17cb37f2586ae.m3u8" -y "/config/transcoding-temp/42b04b6503f3de8e99f17cb37f2586ae%d.ts"
2019-01-24 10:36:57.007 Info App: ProcessRun 'StreamTranscode 6237a7' Started.
2019-01-24 10:36:57.055 Info HttpServer: HTTP GET https://website.com:8097/emby/Items/25230/Images/Primary?tag=c625d83a184fb02fd6cb77f09d50c51a&quality=90. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
2019-01-24 10:36:57.056 Info HttpServer: HTTP GET https://website.com:8097/emby/Items/25230/Images/Logo?tag=88c059d482f82bace5889bd0f26079ab&quality=90. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
2019-01-24 10:36:57.060 Info App: ProcessRun 'StreamTranscode 6237a7' Process exited with code 1
2019-01-24 10:36:57.061 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.0.1.0
	Command line: /usr/lib/emby-server/EmbyServer.dll -programdata /config -ffdetect -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.18.20.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 2
	Program data path: /config
	Application directory: /usr/lib/emby-server
	System.Exception: System.Exception: Error starting ffmpeg
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	
2019-01-24 10:36:57.062 Info HttpServer: HTTP Response 500 to 10.0.10.1. Time: 195ms. https://website.com:8097/emby/videos/24157/hls1/main/209.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NC4wfDE1NDgyOTIyNTc5OTA1&MediaSourceId=d7524cf304559f607331a986c816e494&VideoCodec=h264&AudioCodec=aac&VideoBitrate=139872000&AudioBitrate=128000&PlaySessionId=8939af71f94d451cbe044d63250dc8c5&AudioStreamIndex=1&TranscodingMaxAudioChannels=2&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported
```

Except from transcode log:

```
/usr/bin/ffmpeg -ss 00:20:54.000  -noaccurate_seek -f matroska -i file:"/media/Media/TV Shows/folder/file.mkv" -threads 0 -map 0:0 -map 0:1 -map -0:s -c:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 aac -strict experimental -disposition:a:0 default -ac:a:0 2 -ab:a:0 128000 -af:a:0 "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 6 -segment_time_delta -1254 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 209 -segment_list "/config/transcoding-temp/42b04b6503f3de8e99f17cb37f2586ae.m3u8" -y "/config/transcoding-temp/42b04b6503f3de8e99f17cb37f2586ae%d.ts"

ffmpeg version n4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180831
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, matroska,webm, from 'file:/media/Media/TV Shows/folder/file.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2017-04-06T03:02:38.000000Z
  Duration: 00:43:45.89, start: 0.000000, bitrate: 2587 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x718, SAR 1:1 DAR 640:359, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[segment muxer @ 0x55acf27a3f00] Value -1254.000000 for parameter 'segment_time_delta' out of range [0 - 9.22337e+12]
[segment muxer @ 0x55acf27a3f00] Error setting option segment_time_delta to value -1254.
Could not write header for output file #0 (incorrect codec parameters ?): Numerical result out of range
Error initializing output stream 0:1 -- 
[aac @ 0x55acf27bac80] Qavg: -nan
Conversion failed!
```

**Comment by LukePulverenti** [comment]
How did you install Emby Server? Please make sure you are using our official docker package:
https://emby.media/docker-server.html
Thanks.

**Comment by Aterfax** [comment]
As I said, I am using docker but the https://github.com/binhex/arch-emby version.

As far as I know this is pulling the latest emby from Arch Linux. 

@Binhex You reckon this is anything inside your config causing the issue?

**Comment by LukePulverenti** [comment]
Ok, that docker will need to go back to ffmpeg 4.0.2. Thanks.
