### ISSUE TITLE
Throw pathTooLongException and can't update metadata.

### ISSUE THREAD

**Issue by zheolls** [MediaBrowser/Emby#3562]
I mount google drive on my centos 7 using rclone. 
After I restart, I can never update my metadata.
This is logs:
`2019-07-21 17:32:01.972 Error App: Error validating images for /root/gdriver/jav
	*** Error Report ***
	Version: 4.1.1.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-rpm_{version}_x86_64.rpm
	Operating system: Unix 3.10.0.957
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 1
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.IO.PathTooLongException: System.IO.PathTooLongException: The path '/root/gdriver/jav' is too long, or a component of the specified path is too long.
	   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
	   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
	   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
	   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetFiles(BaseItem item, Boolean includeDirectories, IDirectoryService directoryService)
	   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
	   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
	   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
	Source: System.IO.FileSystem
	TargetSite: Void FindNextEntry()`

**Comment by LukePulverenti** [comment]
Hmm, that looks like it's coming from the .net core runtime.

**Comment by zheolls** [comment]
> Hmm, that looks like it's coming from the .net core runtime.

How can I fix it?

**Comment by LukePulverenti** [comment]
I'm not sure at the moment. I wouldn't have expected the runtime to throw that exception on linux.

**Comment by zheolls** [comment]
> I'm not sure at the moment. I wouldn't have expected the runtime to throw that exception on linux.

I delete the long-name file, then it works again. I suggest that you can ignore long-name files or box a window to remind users.

**Comment by LukePulverenti** [comment]
Thanks, yes that makes sense.
