### ISSUE TITLE
similar errors filling the logs

### ISSUE THREAD

**Issue by mathroc** [MediaBrowser/Emby#3564]
This is when running emby with the docker image (4.2.0.40 but it's been doing that for a while)

```
2019-07-26 20:34:42.955 Error ImageProcessor: Error in image enhancer: CoverArtTrailerEnhancer
        *** Error Report ***
        Version: 4.2.0.40
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Unix 4.13.16.100
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Runtime: file:///system/System.Private.CoreLib.dll
        Processor count: 8
        Program data path: /config
        Application directory: /system
        System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
           at CoverArt.Enhancers.CoverArtBaseEnhancer.Supports(BaseItem item, ImageType imageType)
           at Emby.Drawing.ImageProcessor.GetSupportedEnhancers(BaseItem item, ImageType imageType)
        Source: CoverArt
        TargetSite: Boolean Supports(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Entities.ImageType)

2019-07-26 20:34:42.955 Error ImageProcessor: Error in image enhancer: CoverArtVideoEnhancer
        *** Error Report ***
        Version: 4.2.0.40
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Unix 4.13.16.100
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Runtime: file:///system/System.Private.CoreLib.dll
        Processor count: 8
        Program data path: /config
        Application directory: /system
        System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
           at CoverArt.Enhancers.CoverArtBaseEnhancer.Supports(BaseItem item, ImageType imageType)
           at Emby.Drawing.ImageProcessor.GetSupportedEnhancers(BaseItem item, ImageType imageType)
        Source: CoverArt
        TargetSite: Boolean Supports(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Entities.ImageType)
```

the errors looks like they are always exactly the same except for the enhancer name (but always CoverSomethingEnhancer)

**Comment by LukePulverenti** [comment]
This was an issue in a beta version a couple months back. It was discussed in the Testing Area of the community. To resolve this, simply manually install the latest version of the cover art plugin. Thanks.
