### ISSUE TITLE
Conversion is broken 

### ISSUE THREAD

**Issue by yuriw** [MediaBrowser/Emby#3624]
This is at the end of conversion process:

2020-07-08 14:03:46.216 Error App: Error transferring sync job file
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.109
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.NotSupportedException: System.NotSupportedException: Stream does not support writing.
	   at System.IO.StreamHelpers.ValidateCopyToArgs(Stream source, Stream destination, Int32 bufferSize)
	   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
	   at Emby.Server.Implementations.IO.ManagedFileSystem.CopyFileUsingStreams(String source, String target, Boolean overwrite)
	   at Emby.Server.Implementations.IO.ManagedFileSystem.CopyFile(String source, String target, Boolean overwrite)
	   at Emby.Server.Sync.ConvertSyncProvider.SendFile(SyncJob job, String originalMediaPath, String inputPath, Boolean isMedia, String[] pathParts, SyncTarget target, IProgress`1 progress, CancellationToken cancellationToken)
	   at Emby.Server.Sync.MediaSync.SendFile(SyncJob job, String originalMediaPath, IServerSyncProvider provider, String inputPath, Boolean isMedia, String[] pathParts, SyncTarget target, SyncOptions options, IProgress`1 progress, CancellationToken cancellationToken)
	   at Emby.Server.Sync.MediaSync.GetItem(IServerSyncProvider provider, SyncTarget target, SyncJobItem jobItem, IProgress`1 progress, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
	TargetSite: Void ValidateCopyToArgs(System.IO.Stream, System.IO.Stream, Int32)

**Comment by LukePulverenti** [comment]
Can you please attach the complete emby server log? Also did you open a topic in our community about this? I vaguely recall a similar report there. Thanks.

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
