### ISSUE TITLE
"Error processing request" andorid tv clients stops streamig

### ISSUE THREAD

**Issue by yuriw** [MediaBrowser/Emby#3625]
Streaming stopped on  androidtv 1.8.10g client with error "Too many errors"

In the emby log see this:

2020-07-09 09:47:20.982 Info HttpServer: HTTP Response 200 to 192.168.70.12. Time: 25907ms. http://192.168.90.5:8096/emby/videos/908419/hls1/main/247.ts?DeviceId=cef253b87cb640f9&MediaSourceId=befc6e2046ee12272474b888fbb530b3&PlaySessionId=7d15fd3c42ec4229a01b54e624895989&VideoCodec=h264,mpeg2video,hevc,h265&AudioCodec=aac_latm,mp4a_latm,aac,mp3&VideoBitrate=79616000&AudioBitrate=384000&MaxHeight=2160&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&CopyTimestamps=true&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&hevc-profile=Main,Main10&aac_latm-audiochannels=2&mp4a_latm-audiochannels=2&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=DirectPlayError,AudioCodecNotSupported&AllowVideoStreamCopy=false
2020-07-09 09:47:20.999 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.109
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.Exception: System.Exception: Error starting ffmpeg
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	
2020-07-09 09:47:20.999 Info HttpServer: HTTP Response 500 to 192.168.70.12. Time: 922ms. http://192.168.90.5:8096/emby/videos/908419/hls1/main/247.ts?DeviceId=cef253b87cb640f9&MediaSourceId=befc6e2046ee12272474b888fbb530b3&PlaySessionId=7d15fd3c42ec4229a01b54e624895989&VideoCodec=h264,mpeg2video,hevc,h265&AudioCodec=aac_latm,mp4a_latm,aac,mp3&VideoBitrate=79616000&AudioBitrate=384000&MaxHeight=2160&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&CopyTimestamps=true&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&hevc-profile=Main,Main10&aac_latm-audiochannels=2&mp4a_latm-audiochannels=2&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=DirectPlayError,AudioCodecNotSupported&AllowVideoStreamCopy=false
2020-07-09 09:47:22.034 Info HttpServer: HTTP GET http://192.168.90.5:8096/emby/videos/908419/hls1/main/247.ts?DeviceId=cef253b87cb640f9&MediaSourceId=befc6e2046ee12272474b888fbb530b3&PlaySessionId=7d15fd3c42ec4229a01b54e624895989&VideoCodec=h264,mpeg2video,hevc,h265&AudioCodec=aac_latm,mp4a_latm,aac,mp3&VideoBitrate=79616000&AudioBitrate=384000&MaxHeight=2160&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&CopyTimestamps=true&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&hevc-profile=Main,Main10&aac_latm-audiochannels=2&mp4a_latm-audiochannels=2&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=DirectPlayError,AudioCodecNotSupported&AllowVideoStreamCopy=false. User-Agent=Emby/1.8.10g (Linux;Android 8.0.0) ExoPlayerLib/2.11.4, Accept-Encoding=identity, Host=192.168.90.5:8096, Connection=Keep-Alive
2020-07-09 09:47:22.039 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.109
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetSegmentResult(StreamState state, String playlistId, String variantPlaylistPath, ReadOnlyMemory`1 segmentPath, String segmentExtension, Int32 segmentIndex, TranscodingJob transcodingJob, CancellationToken cancellationToken)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	
2020-07-09 09:47:22.039 Info HttpServer: HTTP Response 500 to 192.168.70.12. Time: 9ms. http://192.168.90.5:8096/emby/videos/908419/hls1/main/247.ts?DeviceId=cef253b87cb640f9&MediaSourceId=befc6e2046ee12272474b888fbb530b3&PlaySessionId=7d15fd3c42ec4229a01b54e624895989&VideoCodec=h264,mpeg2video,hevc,h265&AudioCodec=aac_latm,mp4a_latm,aac,mp3&VideoBitrate=79616000&AudioBitrate=384000&MaxHeight=2160&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&CopyTimestamps=true&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&hevc-profile=Main,Main10&aac_latm-audiochannels=2&mp4a_latm-audiochannels=2&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=DirectPlayError,AudioCodecNotSupported&AllowVideoStreamCopy=false
2020-07-09 09:47:23.193 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:23.194 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:24.083 Info HttpServer: HTTP GET http://192.168.90.5:8096/emby/videos/908419/hls1/main/247.ts?DeviceId=cef253b87cb640f9&MediaSourceId=befc6e2046ee12272474b888fbb530b3&PlaySessionId=7d15fd3c42ec4229a01b54e624895989&VideoCodec=h264,mpeg2video,hevc,h265&AudioCodec=aac_latm,mp4a_latm,aac,mp3&VideoBitrate=79616000&AudioBitrate=384000&MaxHeight=2160&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&CopyTimestamps=true&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&hevc-profile=Main,Main10&aac_latm-audiochannels=2&mp4a_latm-audiochannels=2&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=DirectPlayError,AudioCodecNotSupported&AllowVideoStreamCopy=false. User-Agent=Emby/1.8.10g (Linux;Android 8.0.0) ExoPlayerLib/2.11.4, Accept-Encoding=identity, Host=192.168.90.5:8096, Connection=Keep-Alive
2020-07-09 09:47:24.086 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.109
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetSegmentResult(StreamState state, String playlistId, String variantPlaylistPath, ReadOnlyMemory`1 segmentPath, String segmentExtension, Int32 segmentIndex, TranscodingJob transcodingJob, CancellationToken cancellationToken)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	
2020-07-09 09:47:24.086 Info HttpServer: HTTP Response 500 to 192.168.70.12. Time: 3ms. http://192.168.90.5:8096/emby/videos/908419/hls1/main/247.ts?DeviceId=cef253b87cb640f9&MediaSourceId=befc6e2046ee12272474b888fbb530b3&PlaySessionId=7d15fd3c42ec4229a01b54e624895989&VideoCodec=h264,mpeg2video,hevc,h265&AudioCodec=aac_latm,mp4a_latm,aac,mp3&VideoBitrate=79616000&AudioBitrate=384000&MaxHeight=2160&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&CopyTimestamps=true&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&hevc-profile=Main,Main10&aac_latm-audiochannels=2&mp4a_latm-audiochannels=2&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=DirectPlayError,AudioCodecNotSupported&AllowVideoStreamCopy=false
2020-07-09 09:47:24.423 Info HttpServer: HTTP POST http://192.168.90.5:8096/emby/Sessions/Playing/Stopped. UserAgent: Dalvik/2.1.0 (Linux; U; Android 8.0.0; BRAVIA 4K GB Build/OPR2.170623.027.S32)
2020-07-09 09:47:24.424 Debug PlaystateService: ReportPlaybackStopped PlaySessionId: 7d15fd3c42ec4229a01b54e624895989
2020-07-09 09:47:24.424 Info SessionManager: Playback stopped reported by app AndroidTv 1.8.10g playing The XYZ. Stopped at 739068 ms
2020-07-09 09:47:24.424 Info HttpServer: HTTP Response 204 to 192.168.70.12. Time: 1ms. http://192.168.90.5:8096/emby/Sessions/Playing/Stopped
2020-07-09 09:47:25.385 Info HttpServer: HTTP GET http://192.168.90.5:8096/emby/Users/376bbece91114796ab33c57ca892bb0e/Items/908419?format=json. UserAgent: Dalvik/2.1.0 (Linux; U; Android 8.0.0; BRAVIA 4K GB Build/OPR2.170623.027.S32)
2020-07-09 09:47:25.391 Info HttpServer: HTTP Response 200 to 192.168.70.12. Time: 6ms. http://192.168.90.5:8096/emby/Users/376bbece91114796ab33c57ca892bb0e/Items/908419?format=json
2020-07-09 09:47:25.730 Info HttpServer: HTTP GET http://192.168.90.5:8096/emby/Users/376bbece91114796ab33c57ca892bb0e/Items/908419?format=json. UserAgent: Dalvik/2.1.0 (Linux; U; Android 8.0.0; BRAVIA 4K GB Build/OPR2.170623.027.S32)
2020-07-09 09:47:25.739 Info HttpServer: HTTP Response 200 to 192.168.70.12. Time: 9ms. http://192.168.90.5:8096/emby/Users/376bbece91114796ab33c57ca892bb0e/Items/908419?format=json
2020-07-09 09:47:27.854 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:27.856 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:28.067 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:28.068 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:32.491 Info HttpServer: HTTP GET http://192.168.90.5:8096/emby/Items/908419/Images/Backdrop/0?Accept=webp&MaxWidth=1200&EnableImageEnhancers=true&Tag=9f09b4aed095e324c5f0d751e1b626cb. UserAgent: Dalvik/2.1.0 (Linux; U; Android 8.0.0; BRAVIA 4K GB Build/OPR2.170623.027.S32)
2020-07-09 09:47:32.532 Info HttpServer: HTTP Response 200 to 192.168.70.12. Time: 41ms. http://192.168.90.5:8096/emby/Items/908419/Images/Backdrop/0?Accept=webp&MaxWidth=1200&EnableImageEnhancers=true&Tag=9f09b4aed095e324c5f0d751e1b626cb
2020-07-09 09:47:33.192 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:33.194 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:34.445 Debug HttpServer: WebSocket ConnectionClosedPrematurely
2020-07-09 09:47:34.445 Debug SessionManager: Removing active session Fire TV 4K 2 49b4dbeb49f4101c
2020-07-09 09:47:34.445 Debug SessionManager: Disposing session controller WebSocketController
2020-07-09 09:47:37.856 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:37.858 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:38.067 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:38.068 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:43.194 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:43.195 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:47.857 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:47.858 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:48.066 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:48.068 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:53.193 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:53.194 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:57.872 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:57.873 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:47:58.066 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:47:58.072 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 6ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:03.194 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:03.196 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:07.859 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:07.860 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:08.066 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:08.067 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:13.195 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:13.198 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 3ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:17.854 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:17.856 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:18.066 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:18.067 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 1ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:23.193 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:23.195 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true
2020-07-09 09:48:27.854 Info HttpServer: HTTP GET http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2020-07-09 09:48:27.856 Info HttpServer: HTTP Response 200 to 192.168.90.3. Time: 2ms. http://emby.wawona.lan:8096/ScheduledTasks?IsEnabled=true

It might be media type related, the file info:

Media Info
Video
Title1080p H264
CodecH264
AVCYes
ProfileHigh
Level40
Resolution1920x1040
Aspect Ratio24:13
AnamorphicNo
InterlacedNo
Framerate23.976
Bitrate1,465 kbps
Color Primariesbt709
Color Spacebt709
Color Transferbt709
Bit Depth8 bit
Pixel Formatyuv420p
Reference Frames1
NAL4
Audio
TitleEnglish DTS-HD MA 5.1 (Default)
LanguageEnglish
CodecDTS
ProfileDTS-HD MA
Layout5.1
Channels6 ch
Sample Rate48,000 Hz
Bit Depth24 bit
DefaultYes
Subtitle
TitleEnglish (SUBRIP)
LanguageEnglish
CodecSUBRIP
DefaultNo
ForcedNo
ExternalNo
Containermkv
Path/media/backup/Public/Videos/XYX, The (1996)/The XYZ.mkv
Size1250MB

**Comment by LukePulverenti** [comment]
Hi there, are you still seeing this with Emby Server 4.5.2 and the latest version of the android app?

**Comment by yuriw** [comment]
No, it’s gone !

**Comment by LukePulverenti** [comment]
Thanks for the feedback !
