### ISSUE TITLE
System.IO.PathTooLongException

### ISSUE THREAD

**Issue by Akior** [MediaBrowser/Emby#3660]
*** Error Report ***
	Version: 4.6.0.8
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Linux version 5.7.0-050700-generic (kernel@tangerine) (gcc version 9.3.0 (Ubuntu 9.3.0-13ubuntu1), GNU ld (GNU Binutils for Ubuntu) 2.34) #20200608212
	Framework: .NET Core 3.1.8
	OS/Process: x64/x64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 16
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.IO.PathTooLongException: System.IO.PathTooLongException: The path '/tdc-fef/FHD/Приключения Шерлока Холмса и доктора Ватсона∶ Собака Баскервилей' is too long, or a component of the specified path is too long.
	   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
	   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
	   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
	   at System.IO.FileSystemWatcher.StartRaisingEvents()
	   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
	   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
	   at Emby.Server.Implementations.IO.LibraryMonitor.<>c__DisplayClass37_0.<StartWatchingPath>b__0()
	Source: System.IO.FileSystem
	TargetSite: Void FindNextEntry(Byte*, Int32)
	
Any solution except deleting files ?

**Comment by LukePulverenti** [comment]
Hi, this is an issue in the .NET Core runtime. It will be resolved as soon as we update to 5.0, which will be soon.

**Comment by LukePulverenti** [comment]
Resolved in the upcoming 4.7 server release (via updated .net runtime).
