### ISSUE TITLE
IPTV stop playing

### ISSUE THREAD

**Issue by yyysuo** [MediaBrowser/Emby#3684]
OS Information | linux x86_64 Openwrt Koolshare Router V2.37
Kernel Version | 5.4.108
Total CPU | 4
Total memory | 6.2 GB

Docker Version | 20.10.6 (API: 1.41)
Root directory | /mnt/sda3/docker/data
Storage Driver | overlay2
Logging Driver | json-file
Volume Plugins | local
Network Plugins | bridge, host, ipvlan, macvlan, null, overlay

emby docker version 4.6.0.39
Volumn Mapping    /tmp/emby | /mnt/trans
Transcoding cache folder: /mnt/trans
container's memory limit: 4GB
tmpfs size: 2.9GB
vedio card: HD620
hard transcode api: quick sync and vaapi (all of them have same problem)

Cache file delete script execute every 1m, if file number greate than 120，delete the oldest 100 cache files.

#!/bin/shminitemannite
FILE=`ls /tmp/emby/transcoding-temp/*.ts -l|grep "^-"| wc -l`
if [ ${FILE} -ge 120 ];then
find /tmp/emby/transcoding-temp/*.ts -type f -size +50M -exec rm -rf {} \;
ls /tmp/emby/transcoding-temp/*.ts -t|tail -100|xargs rm -rf
else
    exit 0
fi

play film works fine, when play IPTV, there are some phenomenons
1: IPTV play normally about 30 mins
And picture freeze for mins and stop playing
2: OS cached memory growing to 4GB

I don's understand why film works fine but IPTV stop playing.

**Comment by yyysuo** [comment]
ffmpeg log:
08:01:36.172 [segment @ 0xc9b600] Opening '/mnt/trans/transcoding-temp/C346A1_353.ts.tmp' for writing
08:01:36.466 frame=26490 fps= 25 q=17.0 size= 1319288kB time=00:17:40.44 bitrate=10225.9kbits/s throttle=off speed=   1x    
08:01:36.971 frame=26500 fps= 25 q=15.0 size= 1319775kB time=00:17:40.82 bitrate=10225.9kbits/s throttle=off speed=0.999x    
08:01:37.474 frame=26514 fps= 25 q=17.0 size= 1320377kB time=00:17:41.40 bitrate=10225.0kbits/s throttle=off speed=   1x    
08:01:37.982 frame=26526 fps= 25 q=17.0 size= 1320921kB time=00:17:41.83 bitrate=10225.1kbits/s throttle=off speed=0.999x    
08:01:38.484 frame=26541 fps= 25 q=16.0 size= 1321643kB time=00:17:42.43 bitrate=10224.9kbits/s throttle=off speed=   1x    
08:01:38.985 frame=26550 fps= 25 q=16.0 size= 1322100kB time=00:17:42.81 bitrate=10224.7kbits/s throttle=off speed=0.999x    
08:01:39.192 [segment @ 0xc9b600] Opening '/mnt/trans/transcoding-temp/C346A1.m3u8.tmp' for writing
08:01:39.192 SegmentComplete=video:0 Index=353 Start=1059.600000 End=1062.600000 Duration=3.000000 offset_pts=0 start_pts=1059600000 Frames=75 filename=hls/C346A1/C346A1_353.ts
08:01:39.193 [segment @ 0xc9b600] Opening '/mnt/trans/transcoding-temp/C346A1_354.ts.tmp' for writing
08:01:39.487 frame=26566 fps= 25 q=17.0 size= 1323049kB time=00:17:43.46 bitrate=10225.8kbits/s throttle=off speed=   1x    
08:01:39.990 frame=26576 fps= 25 q=16.0 size= 1323544kB time=00:17:43.87 bitrate=10225.7kbits/s throttle=off speed=0.999x    
08:01:40.497 frame=26589 fps= 25 q=17.0 size= 1324187kB time=00:17:44.40 bitrate=10225.5kbits/s throttle=off speed=0.999x    
08:01:41.004 frame=26601 fps= 25 q=16.0 size= 1324791kB time=00:17:44.88 bitrate=10225.6kbits/s throttle=off speed=0.999x    
08:01:41.508 frame=26616 fps= 25 q=16.0 size= 1325543kB time=00:17:45.45 bitrate=10225.8kbits/s throttle=off speed=   1x    
08:01:41.913 av_interleaved_write_frame(): **No space left on device**






emby server log:
2021-04-20 08:01:41.966 Error SharedHttpPipelineSource: Give up retries copying live stream http://10.10.10.1:11111/rtp/239.253.242.77:8000
	*** Error Report ***
	Version: 4.6.0.39
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.108 (fw867@koolshare.cn) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r16922-8d6ceae547)) #0 SMP Tue Mar 30 11:26:10 2021
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 3
	Data path: /config
	Application path: /system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at System.IO.Pipelines.Pipe.CommitUnsynchronized()
	   at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
	   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
	   at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
	   at System.IO.Pipelines.PipeWriter.CopyFromAsync(Stream source, CancellationToken cancellationToken)
	   at Emby.LiveTV.TunerHosts.SharedHttpPipelineSource.<>c__DisplayClass8_0.<<StartStreaming>b__0>d.MoveNext()
	Source: System.IO.Pipelines
	TargetSite: Boolean CommitUnsynchronized()



2021-04-20 08:01:42.018 Info SharedHttpPipelineSource: SharedHttpPipelineSource is done streaming.
2021-04-20 08:01:42.018 Info SharedHttpPipelineSource: Deleting temp files /mnt/trans/transcoding-temp/8e4fdfb972574c43b661759216506bb8.ts
2021-04-20 08:01:42.018 Error GraphRunner: GraphRunnerTimestampFixup
	*** Error Report ***
	Version: 4.6.0.39
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.108 (fw867@koolshare.cn) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r16922-8d6ceae547)) #0 SMP Tue Mar 30 11:26:10 2021
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 3
	Data path: /config
	Application path: /system
	System.AggregateException: System.AggregateException: One or more errors occurred. (No space left on device)
	 ---> System.IO.IOException: No space left on device
	   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
	   at System.IO.FileStream.FlushWriteBuffer()
	   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
	   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
	   at Emby.TV.TsProcessor.DataFlow.Output.FileStreamWriter.ProcessPackets(TsPacketGroup tsPackets)
	   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
	   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
	   --- End of inner exception stack trace ---
	Source: 
	TargetSite: 
	No Stack Trace Available
	InnerException: System.IO.IOException: No space left on device
	Source: System.Private.CoreLib
	TargetSite: Void WriteNative(System.ReadOnlySpan`1[System.Byte])
	DataflowMessageValue: Emby.TV.TsProcessor.Model.Packets.TsPacketGroup
	   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
	   at System.IO.FileStream.FlushWriteBuffer()
	   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
	   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
	   at Emby.TV.TsProcessor.DataFlow.Output.FileStreamWriter.ProcessPackets(TsPacketGroup tsPackets)
	   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
	   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()

**Comment by LukePulverenti** [comment]
Hi, are you still having an issue with this?

**Comment by yyysuo** [comment]
Yes, I still have this problem after I update to 4.6.1.0.

**Comment by LukePulverenti** [comment]
@yyysuo do you still see this with 4.6.4?

**Comment by yyysuo** [comment]
> @yyysuo do you still see this with 4.6.4?

Yes, I still have this problem

**Comment by LukePulverenti** [comment]
Hi, are you still seeing this with Emby Server 4.7.5?

**Comment by ghost** [comment]
I'm seeing this with 4.7.11.0

**Comment by LukePulverenti** [comment]
Hi, can you please try this again with Emby Server 4.8.10? Thanks.

**Comment by yyysuo** [comment]
I'm very sorry. I'm not very professional, and I have already replaced the main router system and even the entire setup, so I can no longer verify this issue. I will close this issue. Sorry for the trouble caused.
