### ISSUE TITLE
Douban plugin System.MissingMethodException

### ISSUE THREAD

**Issue by Aodi** [MediaBrowser/Emby#3688]
I get a problem with qnap emby server. Douban plugin can't refresh Metadata, error log is following.
[embyserver.txt](https://github.com/MediaBrowser/Emby/files/6538368/embyserver.txt)

```log
2021-05-25 17:37:54.329 Error App: Error in Douban
	*** Error Report ***
	Version: 4.6.0.50
	Command line: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/system/EmbyServer.dll -programdata /share/CACHEDEV1_DATA/.qpkg/EmbyServer/programdata -ffdetect /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffdetect -ffmpeg /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffmpeg -ffprobe /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffprobe -defaultdirectory /share/CACHEDEV1_DATA -updatepackage emby-server-qnap_{version}_x86_64.qpkg -noautorunwebapp
	Operating system: Linux version 4.14.24-qnap (root@U16BuildServer114) (gcc version 4.9.2 (toolchain config: [gcc-4.9.2 binutils-2.25 glibc-2.21])) #1 SMP Sat May 15 07:
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: share/CACHEDEV1_DATA/.qpkg/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/programdata
	Application path: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/system
	System.MissingMethodException: System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> MediaBrowser.Controller.Providers.ItemLookupInfo.get_ProviderIds()'.
	   at Douban.DoubanMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
	   at Douban.DoubanMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(BaseItem originalItem, MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	Source: Douban
	TargetSite: Void MoveNext()
	
```

**Comment by LukePulverenti** [comment]
Hi, I'm pushing a compatibility update, but Douban has gone commercial and is no longer free, so I'm not sure it will work anyway. But please try. Thanks.
