### ISSUE TITLE
Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.

### ISSUE THREAD

**Issue by soupli** [MediaBrowser/Emby#3705]
Movies library is not shown and returns a http 500 error

GET:  
`http://servi:8096/emby/Users/8b875a5328284a5783ddc09214783205/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Movie&Recursive=true&Fields=BasicSyncInfo%2CCanDelete%2CPrimaryImageAspectRatio%2CCommunityRating%2CCriticRating&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&StartIndex=0&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&GroupItemsIntoCollections=true&Limit=50&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Opera&X-Emby-Device-Id=e8f2ebd4-9857-417e-8262-3a0a82411145&X-Emby-Client-Version=4.6.4.0&X-Emby-Token=1eda71cde13a40198b7z8afb33712785`

RESPONSE:  
`Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.`

![image](https://user-images.githubusercontent.com/1036817/133420976-3a09b07c-a9cf-452d-aa3e-08d4014a987c.png)

---

Log:  
```txt
2021-09-15 12:44:14.685 Info LibraryMonitor: Watching directory /data/series/1tb_b
2021-09-15 12:44:14.689 Info LibraryMonitor: Watching directory /data/movies/1tb/The island (2005) 1080p_x264_Dts - NL sub
2021-09-15 12:44:14.689 Info LibraryMonitor: Watching directory /data/movies/1tb_ffwd_a
2021-09-15 12:44:14.693 Info LibraryMonitor: Watching directory /data/movies/1tb_ffwd_b
2021-09-15 12:44:14.693 Info LibraryMonitor: Watching directory /data/series/1tb_ffwd_a
2021-09-15 12:44:14.693 Info LibraryMonitor: Watching directory /data/series/1tb
2021-09-15 12:44:14.825 Info Server: http/1.1 GET http://servi:8096/emby/Users/8b875a5328284a5783ddc09214783205/Items/f137a2dd21bbc1b99aa5c0f6bf02a805?X-Emby-Client=Emby Web&X-Emby-Device-Name=Opera&X-Emby-Device-Id=e8f2ebd4-9857-417e-8262-3a0a82411145&X-Emby-Client-Version=4.6.4.0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 OPR/78.0.4093.184
2021-09-15 12:44:14.827 Debug SqliteItemRepository: GetInternalId from f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805
2021-09-15 12:44:14.840 Debug SqliteItemRepository: GetSubviews total time: 13.2067ms
2021-09-15 12:44:14.841 Info Server: http/1.1 Response 200 to 192.168.1.168. Time: 17ms. http://servi:8096/emby/Users/8b875a5328284a5783ddc09214783205/Items/f137a2dd21bbc1b99aa5c0f6bf02a805?X-Emby-Client=Emby Web&X-Emby-Device-Name=Opera&X-Emby-Device-Id=e8f2ebd4-9857-417e-8262-3a0a82411145&X-Emby-Client-Version=4.6.4.0
2021-09-15 12:44:14.869 Info Server: http/1.1 GET http://servi:8096/emby/Users/8b875a5328284a5783ddc09214783205/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Movie&Recursive=true&Fields=BasicSyncInfo,CanDelete,PrimaryImageAspectRatio,CommunityRating,CriticRating&ImageTypeLimit=1&EnableImageTypes=Primary,Backdrop,Thumb&StartIndex=0&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&GroupItemsIntoCollections=true&Limit=50&X-Emby-Client=Emby Web&X-Emby-Device-Name=Opera&X-Emby-Device-Id=e8f2ebd4-9857-417e-8262-3a0a82411145&X-Emby-Client-Version=4.6.4.0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 OPR/78.0.4093.184
2021-09-15 12:44:14.871 Debug SqliteItemRepository: GetInternalId from f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805
2021-09-15 12:44:14.877 Error Server: Error processing request
	*** Error Report ***
	Version: 4.6.4.0
	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.0-84-generic (buildd@lgw01-amd64-050) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: app/emby/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /app/emby
	SQLitePCL.pretty.SQLiteException: Corrupt: database disk image is malformed
	SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
	   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
	   at SQLitePCL.pretty.StatementImpl.MoveNext()
	   at Emby.Sqlite.SqliteExtensions.ExecuteQuery(IStatement This)+MoveNext()
	   at Emby.Server.Implementations.Data.SqliteItemRepository.QueryItemsInTransaction[T](InternalItemsQuery query, IDatabaseConnection db, String[] columnsToSelect, Func`5 rowReaderFn, Boolean singleResult, String methodName)
	   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItems(InternalItemsQuery query)
	   at MediaBrowser.Controller.Entities.Folder.GetItemsInternal(InternalItemsQuery query)
	   at MediaBrowser.Controller.Entities.CollectionFolder.GetItemsInternal(InternalItemsQuery query)
	   at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
	   at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
	   at MediaBrowser.Api.UserLibrary.ItemsService.GetItems(GetItems request)
	   at MediaBrowser.Api.UserLibrary.ItemsService.Get(GetItems request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: SQLitePCL.pretty
	TargetSite: Void CheckOk(SQLitePCLEx.sqlite3, Int32)
	
2021-09-15 12:44:14.877 Info Server: http/1.1 Response 500 to 192.168.1.168. Time: 8ms. http://servi:8096/emby/Users/8b875a5328284a5783ddc09214783205/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Movie&Recursive=true&Fields=BasicSyncInfo,CanDelete,PrimaryImageAspectRatio,CommunityRating,CriticRating&ImageTypeLimit=1&EnableImageTypes=Primary,Backdrop,Thumb&StartIndex=0&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&GroupItemsIntoCollections=true&Limit=50&X-Emby-Client=Emby Web&X-Emby-Device-Name=Opera&X-Emby-Device-Id=e8f2ebd4-9857-417e-8262-3a0a82411145&X-Emby-Client-Version=4.6.4.0
2021-09-15 12:44:28.762 Info Server: http/1.1 GET http://servi:8096/emby/System/Logs/embyserver.txt. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 OPR/78.0.4093.184
```

[Full log here](https://github.com/MediaBrowser/Emby/files/7169477/log.txt)

---

When i removed the directory containing the corrupted file, the Movies library loads fine. Beneath is an screenshot of a `ls -al` of the directory containing the (corrupted) file(s):

![image](https://user-images.githubusercontent.com/1036817/133422389-fc6b3179-dde2-492b-9748-2dd3620d1c74.png)

**Comment by LukePulverenti** [comment]
Hi, please see here:
https://support.emby.media/support/solutions/articles/44002210894-corrupt-database
Thanks.

**Comment by soupli** [comment]
> Hi, please see here:
> https://support.emby.media/support/solutions/articles/44002210894-corrupt-database
> Thanks.

The issue was resolved by deleting the library.db, library.db-shm & library.db-wal files and Load Fresh. Thanks a lot!
