### ISSUE TITLE
Cannot download images from fanart.tv

### ISSUE THREAD

**Issue by Xm798** [MediaBrowser/Emby#3751]
I cannot get images from fanart.tv, and the log is as follows.

Seems like the url `https://assets.fanart.tv/fanart/movies/752/movieposter/v-for-vendetta-52d567287a841.jpg` can't be accessed, and the correct url that I can access is `https://images.fanart.tv/fanart/v-for-vendetta-52d567287a841.jpg`.

```bash
curl https://assets.fanart.tv/fanart/movies/752/movieposter/v-for-vendetta-52d567287a841.jpg
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to assets.fanart.tv:443
```

```log
2022-11-19 06:28:50.209 Error HttpClient: Error getting response from https://assets.fanart.tv/fanart/movies/752/movieposter/v-for-vendetta-52d567287a841.jpg
	*** Error Report ***
	Version: 4.7.9.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 4.4.180+ (root@build15) (gcc version 8.5.0 (GCC) ) #42661 SMP Fri Apr 1 15:33:06 CST 2022
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /config
	Application path: /system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
	 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
	   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
	   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
	   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
	   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
	Source: System.Net.Security
	TargetSite: Void MoveNext()
	   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
	   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
	   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
```

**Comment by LukePulverenti** [comment]
Hi, are you still running into this? fanart.tv does have occasional issues when they're under heavy load.

**Comment by Xm798** [comment]
> Hi, are you still running into this? fanart.tv does have occasional issues when they're under heavy load.

Sorry for that, I haven't been using fanart recently and use tmdb's image instead, it runs stably.

Thanks for reply!

**Comment by semool** [comment]
i have this problem too. Emby Server 4.7.10. All the fanart.tv Images are not displayed. When i click open in new tab:
The Url: https://mydomain/emby/Images/Remote?api_key=dontknowifthisisunique&imageUrl=https%3A%2F%2Fassets.fanart.tv%2Ffanart%2Fmovies%2F333371%2Fmovieposter%2F10-cloverfield-lane-56be325177fc4.jpg
Message:
Connection refused (assets.fanart.tv:443)

When i remove the front part from the url the Image will be loaded and i can save and set in manualy:
https://assets.fanart.tv/fanart/movies/333371/movieposter/10-cloverfield-lane-56be325177fc4.jpg

**Comment by KodeStar** [comment]
`assets.` is the right url, `images.` is the cloudflare cache for the website. If you have a way of reproducing this reliably @LukePulverenti and want to hop on the fanart.tv discord at some point we can try troubleshooting and getting to the bottom of it.

**Comment by KodeStar** [comment]
Actually, it looks like one of the servers in the round robin config isn't responding... blergh

**Comment by LukePulverenti** [comment]
@Xm798 are you still able to reproduce this?

**Comment by Xm798** [comment]
> @Xm798 are you still able to reproduce this?

I have been utilizing TMDB to download images, and it has been functioning well. Consequently, I haven't had a need to use Fanart anymore.
