### ISSUE TITLE
can not login when using systemctl command  start emby-server

### ISSUE THREAD

**Issue by dzhl** [MediaBrowser/Emby#3782]
I used the systemctl command to start emby-server, but when I tried to log in, it said my password was incorrect. However, if I directly use /opt/emby-server/bin/emby-server, I can log in normally. Can you tell me why this is happening? I'm pretty sure that the password I entered is correct.

**Comment by LukePulverenti** [comment]
Hi, that's a good question. Can you please attach the emby server log? Thanks.

**Comment by dzhl** [comment]
> Hi, that's a good question. Can you please attach the emby server log? Thanks.

2023-05-05 13:38:54.982 Error Server: Access token is invalid or expired.
2023-05-05 13:39:22.184 Error Server: Access token is invalid or expired.
2023-05-05 13:39:30.412 Error Server: Access token is invalid or expired.
2023-05-05 13:39:40.893 Error Server: Access token is invalid or expired.
2023-05-05 13:39:42.551 Error Server: Access token is invalid or expired.
2023-05-05 13:39:47.026 Error Server: Access token is invalid or expired.
2023-05-05 13:41:40.569 Error Server: Access token is invalid or expired.
2023-05-05 13:42:13.437 Error Server: Access token is invalid or expired.
2023-05-05 13:42:55.092 Error Server: Access token is invalid or expired.
2023-05-05 13:44:25.688 Error ImageProcessor: Error encoding image
	*** Error Report ***
	Version: 4.8.0.34
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_arm64.deb
	Operating system: Linux version 5.10.0-19-arm64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1
	Framework: .NET 6.0.14
	OS/Process: arm64/arm64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.Exception: System.Exception: SKCodec had an error reading /var/lib/emby/metadata/library/ff/fff1a2363fbc60b9df6dbbb99738e9c1/poster.png
	   at Emby.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: System.String EncodeImage(System.String, System.String, Boolean, System.Nullable`1[MediaBrowser.Model.Drawing.ImageOrientation], Int32, MediaBrowser.Controller.Drawing.ImageProcessingOptions, MediaBrowser.Model.Drawing.ImageFormat)
	
2023-05-05 13:44:49.624 Error Server: Access token is invalid or expired.
2023-05-05 13:45:07.052 Error Server: Access token is invalid or expired.
2023-05-05 13:46:15.015 Error Server: Access token is invalid or expired.
2023-05-05 13:48:07.154 Error Server: Access token is invalid or expired.
2023-05-05 13:49:08.089 Error Server: Access token is invalid or expired.
2023-05-05 13:49:17.352 Error Server: Access token is invalid or expired.
2023-05-05 13:54:23.627 Error Server: Access token is invalid or expired.
2023-05-05 14:17:21.617 Info HttpClient: GET https://api.github.com/repos/MediaBrowser/Emby.Releases/releases
2023-05-05 14:28:36.182 Info ServerConfigurationManager: Saving system configuration
2023-05-05 14:28:36.208 Info App: Setting default culture to zh-CN
2023-05-05 14:52:06.874 Error SessionManager: Error updating user
	*** Error Report ***
	Version: 4.8.0.34
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_arm64.deb
	Operating system: Linux version 5.10.0-19-arm64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1
	Framework: .NET 6.0.14
	OS/Process: arm64/arm64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	SQLitePCL.pretty.SQLiteException: Error: cannot rollback - no transaction is active
	SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
	   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
	   at SQLitePCL.pretty.StatementImpl.MoveNext()
	   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, ReadOnlySpan`1 sqlUtf8)
	   at SQLitePCL.pretty.DatabaseConnection.RollbackTransaction(IDatabaseConnection This)
	   at Emby.Server.Implementations.Data.SqliteUserRepository.UpdateUser(User user)
	   at Emby.Server.Implementations.Library.UserManager.UpdateUser(User user, Boolean triggerEvent)
	   at Emby.Server.Implementations.Session.SessionManager.LogSessionActivity(String appName, String appVersion, Int64 deviceId, String reportedDeviceId, String deviceName, IPAddress remoteAddress, String protocol, User user)
	Source: SQLitePCL.pretty
	TargetSite: Void CheckOk(SQLitePCLEx.sqlite3, Int32)
	
2023-05-05 14:52:08.745 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.0.34
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_arm64.deb
	Operating system: Linux version 5.10.0-19-arm64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1
	Framework: .NET 6.0.14
	OS/Process: arm64/arm64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	SQLitePCL.pretty.SQLiteException: Error: cannot rollback - no transaction is active
	SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
	   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
	   at SQLitePCL.pretty.StatementImpl.MoveNext()
	   at SQLitePCL.pretty.DatabaseConnect

**Comment by LukePulverenti** [comment]
HI, are you still seeing this with the latest build?

**Comment by LukePulverenti** [comment]
Closing, but if you're still having an issue then please feel free to reopen with the requested information. Thanks.
