### ISSUE TITLE
people thumb can not be loaded

### ISSUE THREAD

**Issue by luke-liuqi** [MediaBrowser/Emby#3844]
hi, when loading local nfo, the people's tmdb thumb urls are already. But on emby server, i can't see the pictures of actor. And there is no file in /config/metadata
<img width="1817" alt="iShot_2024-07-21_09 40 32" src="https://github.com/user-attachments/assets/01da041f-f5b3-4c0a-a358-a0ad7d4fb0fd">
<img width="789" alt="iShot_2024-07-21_09 40 21" src="https://github.com/user-attachments/assets/225e1dd5-36bd-41f0-852b-d3427ec08731">

**Comment by LukePulverenti** [comment]
Hi, please try refreshing the metadata on the movie and see if that helps.

**Comment by luke-liuqi** [comment]
> Hi, please try refreshing the metadata on the movie and see if that helps.
sorry,
it doesn't help, still no file in metadata/people

**Comment by LukePulverenti** [comment]
HI, please attach the emby server log from when you did that. Thanks.

**Comment by luke-liuqi** [comment]
> HI, please attach the emby server log from when you did that. Thanks.

2024-07-22 16:29:36.999 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2024-07-22 16:29:37.124 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/af0d1cf56cc84583a18009b5877ae368.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:37.124 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 112ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/12906/Images/Primary?maxHeight=380&maxWidth=676&tag=2301c468c1ea12c7aad7b169318f321d&quality=90
2024-07-22 16:29:37.139 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/ce6ad8cf5674485987283ff9425400bf.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:37.139 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 126ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/9294/Images/Primary?maxHeight=380&maxWidth=676&tag=0b4f2f2e4bf45f422eaeae839394d5c1&quality=90
2024-07-22 16:29:37.147 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/d724329fcfd54421b60265d39b272693.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:37.147 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 129ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/13831/Images/Primary?maxHeight=380&maxWidth=676&tag=7e308f3f3a5ea72c622364cf9515903d&quality=90
2024-07-22 16:29:37.306 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/ff7d4de31e5549849d92f5e683d72023.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:37.306 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 290ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/8875/Images/Primary?maxHeight=380&maxWidth=676&tag=c207267b2d1f279467a154ac35cdfc1c&quality=90
2024-07-22 16:29:39.688 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/c431d338b54b445a8548159036a0df53.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:39.688 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 85ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/9294/Images/Primary?maxWidth=676&quality=90
2024-07-22 16:29:39.689 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/0b1f2667ab484d939f2f2131d44556e0.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:39.689 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 85ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/13831/Images/Primary?maxWidth=676&quality=90
2024-07-22 16:29:39.700 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/0bb37964642042c2ab93dc41d899edc6.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:39.700 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 96ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/12906/Images/Primary?maxWidth=676&quality=90
2024-07-22 16:29:39.919 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-z4pro-generic (tdx21@tdx21-G7-7590) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #13 SMP
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: SKFileWStream to output path /config/cache/temp/fc5ba461a7a84b40bd76f13bf8d7c36a.png is not valid.
	   at Emby.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(ItemImageInfo[] images, String outputPath, Int32 width, Int32 height)
	   at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateCollage(BaseItem primaryItem, BaseItem[] items, String outputPath, Int32 width, Int32 height, CancellationToken cancellationToken)
	   at Emby.Providers.Images.BaseLazyCollageImageProvider.CreateImage(BaseItem item, BaseItem[] itemsWithImages, String outputPathWithoutExtension, ImageType imageType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: Void BuildThumbCollage(MediaBrowser.Controller.Entities.ItemImageInfo[], System.String, Int32, Int32)
	
2024-07-22 16:29:39.919 Info Server: http/1.1 Response 500 to ‌‍‍192.168.51.182‌. Time: 315ms. GET http://‌‍‍192.168.51.154‌:8096/emby/Items/8875/Images/Primary?maxWidth=676&quality=90
2024-07-22 16:29:41.347 Info Server: http/1.1 POST http://‌‍‍192.168.51.154‌:8096/emby/ScheduledTasks/Running/6330ee8fb4a957f33981f89aa78b030f?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome macOS&X-Emby-Device-Id=TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyNi4wLjAuMCBTYWZhcmkvNTM3LjM2fDE3MjEwMzAwMzAzMjY1&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=‌444d73a46733470aab557e33b2825a4b‌&X-Emby-Language=zh-cn. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
2024-07-22 16:29:41.349 Info TaskManager: Executing Scan media library
2024-07-22 16:29:41.349 Info Server: http/1.1 Response 204 to ‌‍‍192.168.51.182‌. Time: 2ms. POST http://‌‍‍192.168.51.154‌:8096/emby/ScheduledTasks/Running/6330ee8fb4a957f33981f89aa78b030f?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome macOS&X-Emby-Device-Id=TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyNi4wLjAuMCBTYWZhcmkvNTM3LjM2fDE3MjEwMzAwMzAzMjY1&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=‌444d73a46733470aab557e33b2825a4b‌&X-Emby-Language=zh-cn
2024-07-22 16:29:41.649 Info Server: http/1.1 POST http://‌‍‍192.168.51.154‌:8096/Sessions/Playing/Progress. UserAgent: Infuse-Library/7.8
2024-07-22 16:29:41.651 Info Server: http/1.1 Response 204 to ‌‍‍192.168.51.59‌. Time: 3ms. POST http://‌‍‍192.168.51.154‌:8096/Sessions/Playing/Progress
2024-07-22 16:29:43.259 Info App: Removing item from database, Type: Episode, Name: Running Man.S01E714.20240721, Path: /mnt/share/综艺/Running Man (2010)/Running Man.S01E714.20240721.mp4, Id: 13907
2024-07-22 16:29:43.267 Info App: Deleting path /config/metadata/library/66/6692a4bdd3fec1594255de8920f5fa71
2024-07-22 16:29:43.353 Info TaskManager: Scan media library Completed after 0 minute(s) and 1 seconds

**Comment by luke-liuqi** [comment]
> HI, please attach the emby server log from when you did that. Thanks.

2024-07-22 16:37:19.127 Info App: Refresh metadata requested on 9294
2024-07-22 16:37:19.127 Info Server: http/1.1 Response 204 to ‌‍‍192.168.51.182‌. Time: 4ms. POST http://‌‍‍192.168.51.154‌:8096/emby/Items/9294/Refresh?Recursive=true&ImageRefreshMode=FullRefresh&MetadataRefreshMode=FullRefresh&ReplaceAllImages=false&ReplaceAllMetadata=false&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome macOS&X-Emby-Device-Id=TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyNi4wLjAuMCBTYWZhcmkvNTM3LjM2fDE3MjEwMzAwMzAzMjY1&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=‌444d73a46733470aab557e33b2825a4b‌&X-Emby-Language=zh-cn
2024-07-22 16:37:19.205 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i file:"/mnt/share/xx.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-07-22 16:37:19.377 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-07-22 16:37:19.411 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i file:"/mnt/share/xx.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-07-22 16:37:19.560 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded

**Comment by LukePulverenti** [comment]
HI, what metadata fetchers do you have enabled on the library?

**Comment by LukePulverenti** [comment]
@luke-liuqi ?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
