### ISSUE TITLE
Server error for /Library/VirtualFolders/Paths

### ISSUE THREAD

**Issue by Schaka** [MediaBrowser/Emby#3853]
This call is not documented to require a GUID of any sort.
The Emby Token is definitely correct, the previous requests all work just fine. It's only this particular one that's causing issues.

The id that's part of the request body is not a guid. It's the id of the VirtualFolder. I checked what the web ui supplies (matches API docs) and copied what I could from that. Not sure what's going on. 

I can only assume this specific endpoint may require user auth (?) and is missing the user-id entirely?

```
2024-08-28 21:37:30.509 Info Server: http/1.1 POST http://host5:8096/host5/Library/VirtualFolders/Paths?refreshLibrary=false. UserAgent: Java/21.0.3
2024-08-28 21:37:30.510 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.8.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 6.1.0-13-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: /config
	Application path: /system
	System.FormatException: System.FormatException: Unrecognized Guid format.
	   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
	   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
	   at System.Guid..ctor(String g)
	   at MediaBrowser.Controller.Library.LibraryManagerExtensions.GetItemById(ILibraryManager manager, ReadOnlySpan`1 id)
	   at MediaBrowser.Controller.Library.LibraryManagerExtensions.GetItemById(ILibraryManager manager, String id)
	   at Emby.Api.Library.LibraryStructureService.Post(AddMediaPath request)
	   at Emby.Server.Implementations.Services.ServiceController.<>c__DisplayClass8_0.<VoidActionDelegate>b__0(Object service, Object request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req, Type serviceType)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
	TargetSite: Void SetFailure(Boolean, System.String)
	
2024-08-28 21:37:30.510 Info Server: http/1.1 Response 500 to host6. Time: 1ms. POST http://host5:8096/host5/Library/VirtualFolders/Paths?refreshLibrary=false
```

**Comment by LukePulverenti** [comment]
Hi, what are the contents of the request body?

**Comment by Schaka** [comment]
I can't say any more because I think my request body wasn't being serialized properly.

I'm close this and reopen if I can reliably reproduce it for you.
