### ISSUE TITLE
Error App: Error extracting chapter images

### ISSUE THREAD

**Issue by 13521254555** [MediaBrowser/Emby#3862]
2024-11-11 14:17:18.228 Error App: Error extracting chapter images for M:\我的电影\20241101\【未知演员】AMOZ-031\AMOZ-031.mp4
	*** Error Report ***
	Version: 4.9.0.31
	Command line: E:\MYTOOLS\embyserverX64\system\EmbyServer.dll
	Operating system: Microsoft Windows 10.0.26100
	OS/Process: x64/x64
	Framework: .NET 8.0.10
	Runtime: E:/MYTOOLS/embyserverX64/system/System.Private.CoreLib.dll
	Processor count: 8
	Data path: E:\MYTOOLS\embyserverX64\programdata
	Application path: E:\MYTOOLS\embyserverX64\system
	System.InvalidOperationException: System.InvalidOperationException: An extension of the same type has already been added.
	   at Emby.ProcessRun.Runners.ProcessRunnerExtensible.AddExtension[T](T newExtension)
	   at Emby.Server.MediaEncoding.Unified.Ffmpeg.ImageExtractRunner.OnInitialize()
	   at Emby.ProcessRun.Runners.ProcessRunnerExtensible.OnBeforeStartProcessCore(StartParams processStartInfo)
	   at Emby.ProcessRun.Runners.ProcessRunnerBase.Run(StartParams startParams)
	   at Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunnerBase.Start(String commandLineArgs)
	   at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractorBase.RunExtraction(String inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 protocol, Nullable`1 streamIndex, Nullable`1 threedFormat, Nullable`1 startOffset, Nullable`1 interval, String targetDirectory, String targetFilename, Nullable`1 maxWidth, Boolean enableThumbnailFilter, CancellationToken cancellationToken)
	   at Emby.Providers.MediaInfo.ThumbnailGenerator.QuickRefreshChapterImages(Video video, MediaStream videoStream, ReadOnlyMemory`1 inputPath, MediaProtocol protocol, IDirectoryService directoryService, List`1 chapters, List`1 currentImages, Boolean saveChapters, CancellationToken cancellationToken)
	Source: Emby.ProcessRun
	TargetSite: Void AddExtension[T](T)

**Comment by LukePulverenti** [comment]
Hi, please follow along here: https://emby.media/community/index.php?/topic/133648-bug-image-extraction-not-working-since-49031-beta/
Thanks.
