### ISSUE TITLE
Embedded album cover display issue in a song

### ISSUE THREAD

**Issue by StefanLuo** [MediaBrowser/Emby#3863]
Since a certain version, the embedded album cover in song files can no longer be displayed, whereas it worked fine before.
![image](https://github.com/user-attachments/assets/92baf81d-df78-4e67-a511-e3ec613abbd5)

**Comment by LukePulverenti** [comment]
Hi, what image fetchers are enabled on the library?

**Comment by StefanLuo** [comment]
> Hi, what image fetchers are enabled on the library?

Hi, I just enabled the two Fetchers as shown in the picture.
![image](https://github.com/user-attachments/assets/69b3f575-287a-4188-8462-f85fdf014abe)

**Comment by LukePulverenti** [comment]
OK please try refreshing the metadata on that track and see if that helps. If there's still no image, then please attach the emby server log. Thanks.

**Comment by StefanLuo** [comment]
> OK please try refreshing the metadata on that track and see if that helps. If there's still no image, then please attach the emby server log. Thanks.

Hi,
Here is the log:
2024-11-16 14:33:30.981 Error QuickSingleImageExtractor: QuickSingleImageExtractor.RunExtraction [C9185D496598]: Error running quick-extract-image -f flac -threads 1 -i file:"E:\115\影视分享\音乐\婚礼歌单\仪式音乐\Can't Help Falling In Love.flac" -map 0:1 -update 1 -vsync 0 -f image2 "C:\Users\Administrator\AppData\Roaming\Emby-Server\programdata\cache\temp\59f5cf2a-69af-4a9f-a29e-10cd6f58db94.jpg"
*** Error Report ***
Version: 4.9.0.31
Command line: C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll
Operating system: Microsoft Windows 10.0.20348
OS/Process: x64/x64
Framework: .NET 8.0.10
Runtime: C:/Users/Administrator/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
Processor count: 4
Data path: C:\Users\Administrator\AppData\Roaming\Emby-Server\programdata
Application path: C:\Users\Administrator\AppData\Roaming\Emby-Server\system
System.InvalidOperationException: System.InvalidOperationException: An extension of the same type has already been added.
at Emby.ProcessRun.Runners.ProcessRunnerExtensible.AddExtension[T](T newExtension)
at Emby.Server.MediaEncoding.Unified.Ffmpeg.ImageExtractRunner.OnInitialize()
at Emby.ProcessRun.Runners.ProcessRunnerExtensible.OnBeforeStartProcessCore(StartParams processStartInfo)
at Emby.ProcessRun.Runners.ProcessRunnerBase.Run(StartParams startParams)
at Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunnerBase.Start(String commandLineArgs)
at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractorBase.RunExtraction(String inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 protocol, Nullable`1 streamIndex, Nullable`1 threedFormat, Nullable`1 startOffset, Nullable`1 interval, String targetDirectory, String targetFilename, Nullable`1 maxWidth, Boolean enableThumbnailFilter, CancellationToken cancellationToken)
Source: Emby.ProcessRun
TargetSite: Void AddExtension[T](T)

2024-11-16 14:33:30.982 Error App: Error in Embedded Images
*** Error Report ***
Version: 4.9.0.31
Command line: C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll
Operating system: Microsoft Windows 10.0.20348
OS/Process: x64/x64
Framework: .NET 8.0.10
Runtime: C:/Users/Administrator/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
Processor count: 4
Data path: C:\Users\Administrator\AppData\Roaming\Emby-Server\programdata
Application path: C:\Users\Administrator\AppData\Roaming\Emby-Server\system
System.InvalidOperationException: System.InvalidOperationException: An extension of the same type has already been added.
at Emby.ProcessRun.Runners.ProcessRunnerExtensible.AddExtension[T](T newExtension)
at Emby.Server.MediaEncoding.Unified.Ffmpeg.ImageExtractRunner.OnInitialize()
at Emby.ProcessRun.Runners.ProcessRunnerExtensible.OnBeforeStartProcessCore(StartParams processStartInfo)
at Emby.ProcessRun.Runners.ProcessRunnerBase.Run(StartParams startParams)
at Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunnerBase.Start(String commandLineArgs)
at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractorBase.RunExtraction(String inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 protocol, Nullable`1 streamIndex, Nullable`1 threedFormat, Nullable`1 startOffset, Nullable`1 interval, String targetDirectory, String targetFilename, Nullable`1 maxWidth, Boolean enableThumbnailFilter, CancellationToken cancellationToken)
at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractionManager.ExtractImageInternal(ReadOnlyMemory`1 inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 streamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useThumbNailFilter, CancellationToken cancellationToken)
at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractionManager.ExtractImage(ReadOnlyMemory`1 inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 streamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
at Emby.Providers.MediaInfo.AudioImageProvider.GetImage(Audio item, LibraryOptions libraryOptions, List`1 imageStreams, CancellationToken cancellationToken)
at Emby.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseMetadataResult itemResult, IDynamicImageProvider provider, Boolean providerReportsChanges, ImageRefreshOptions refreshOptions, Boolean replaceAllImages, TypeOptions savedOptions, LibraryOptions libraryOptions, List`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
Source: Emby.ProcessRun
TargetSite: Void AddExtension[T](T)

**Comment by LukePulverenti** [comment]
OK you're on the beta. It's resolved for the next build. Thanks.
