### ISSUE TITLE
Playing media items on Android fails (VLC with Yatse)

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/Emby#3867]
In the past this has worked like a charm. But now movies do not play anymore. "Just Player" also does not work.

1. I open Yatse android app, navigate my library
2. click on movie
3. select VLC to play the selected item
4. VLC starts, but nothing is played and everything stays black

FP3+
LineageOS 21 20241211
VLC 3.5.7
Yatse 11.8.0

No entries in transcode log.

```
2024-12-17 15:12:43.585 Info Server: http/1.1 POST http://host1/Users/4fc58f9d987d40bbac9903d929d391a4/PlayingItems/268691/Progress. Source Ip: host2, UserAgent: okhttp/5.0.0-alpha.14
2024-12-17 15:12:43.585 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 6.1.0-28-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: /config
	Application path: /system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
	   at System.ThrowHelper.ThrowArgumentNullException(String name)
	   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	   at MediaBrowser.Controller.Session.SessionInfo.GetOrAddPlaySessionInfo(PlaybackProgressInfo info)
	   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, SessionInfo session)
	   at Emby.Server.MediaEncoding.Api.PlaystateService.Post(ReportPlaybackProgress request)
	   at Emby.Server.MediaEncoding.Api.PlaystateService.Post(OnPlaybackProgress request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req, Type serviceType)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: System.Collections.Concurrent
	TargetSite: Void ThrowArgumentNullException(System.String)
	
2024-12-17 15:12:43.585 Info Server: http/1.1 Response 400 to host2. Time: 1ms. POST http://host1/Users/4fc58f9d987d40bbac9903d929d391a4/PlayingItems/268691/Progress
2024-12-17 15:12:43.591 Info Server: http/1.1 POST http://host1/Items/268691/PlaybackInfo?UserId=4fc58f9d987d40bbac9903d929d391a4&AutoOpenLiveStream=true&StartTimeTicks=0&MaxStreamingBitrate=4000000. Source Ip: host2, UserAgent: okhttp/5.0.0-alpha.14
2024-12-17 15:12:43.592 Info App: User policy for myUserName. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-12-17 15:12:43.592 Info App: Bitrate exceeds DirectPlay limit: media bitrate: 6934581, max bitrate: 4000000
2024-12-17 15:12:43.592 Info App: Bitrate exceeds DirectStream limit: media bitrate: 6934581, max bitrate: 4000000
2024-12-17 15:12:43.593 Info App: Bitrate exceeds DirectPlay limit: media bitrate: 6934581, max bitrate: 4000000
2024-12-17 15:12:43.593 Info App: Bitrate exceeds DirectStream limit: media bitrate: 6934581, max bitrate: 4000000
2024-12-17 15:12:43.593 Info App: Bitrate exceeds DirectPlay limit: media bitrate: 6934581, max bitrate: 4000000
2024-12-17 15:12:43.593 Info App: Bitrate exceeds DirectStream limit: media bitrate: 6934581, max bitrate: 4000000
2024-12-17 15:12:43.593 Info SessionManager: Adding playSession 1e1980d39f9c4149b2633091eb52cfb2 to session 9a7499027c3cdca4203b15c8a6ba0741
2024-12-17 15:12:43.594 Info Server: http/1.1 Response 200 to host2. Time: 3ms. POST http://host1/Items/268691/PlaybackInfo?UserId=4fc58f9d987d40bbac9903d929d391a4&AutoOpenLiveStream=true&StartTimeTicks=0&MaxStreamingBitrate=4000000
2024-12-17 15:12:43.641 Info Server: http/1.1 POST http://host1/Users/4fc58f9d987d40bbac9903d929d391a4/PlayingItems/268691/Progress. Source Ip: host2, UserAgent: okhttp/5.0.0-alpha.14
2024-12-17 15:12:43.642 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 6.1.0-28-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: /config
	Application path: /system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
	   at System.ThrowHelper.ThrowArgumentNullException(String name)
	   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	   at MediaBrowser.Controller.Session.SessionInfo.GetOrAddPlaySessionInfo(PlaybackProgressInfo info)
	   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, SessionInfo session)
	   at Emby.Server.MediaEncoding.Api.PlaystateService.Post(ReportPlaybackProgress request)
	   at Emby.Server.MediaEncoding.Api.PlaystateService.Post(OnPlaybackProgress request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req, Type serviceType)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: System.Collections.Concurrent
	TargetSite: Void ThrowArgumentNullException(System.String)
	
2024-12-17 15:12:43.642 Info Server: http/1.1 Response 400 to host2. Time: 1ms. POST http://host1/Users/4fc58f9d987d40bbac9903d929d391a4/PlayingItems/268691/Progress
2024-12-17 15:12:43.709 Info Server: http/1.1 POST http://host1/Users/4fc58f9d987d40bbac9903d929d391a4/PlayingItems/268691/Progress. Source Ip: host2, UserAgent: okhttp/5.0.0-alpha.14
2024-12-17 15:12:43.711 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 6.1.0-28-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: /config
	Application path: /system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
	   at System.ThrowHelper.ThrowArgumentNullException(String name)
	   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	   at MediaBrowser.Controller.Session.SessionInfo.GetOrAddPlaySessionInfo(PlaybackProgressInfo info)
	   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, SessionInfo session)
	   at Emby.Server.MediaEncoding.Api.PlaystateService.Post(ReportPlaybackProgress request)
	   at Emby.Server.MediaEncoding.Api.PlaystateService.Post(OnPlaybackProgress request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req, Type serviceType)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: System.Collections.Concurrent
	TargetSite: Void ThrowArgumentNullException(System.String)
	
2024-12-17 15:12:43.711 Info Server: http/1.1 Response 400 to host2. Time: 2ms. POST http://host1/Users/4fc58f9d987d40bbac9903d929d391a4/PlayingItems/268691/Progress
2024-12-17 15:12:45.914 Info Server: http/1.1 GET http://host1:443/videos/268691/master.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit. Source Ip: host2, Accept=*/*, Connection=close, Host=host16, User-Agent=VLC/3.0.19 LibVLC/3.0.19, Accept-Language=en_US, Range=bytes=0-, X-Forwarded-For=host17, X-Forwarded-Host=host1, X-Forwarded-Method=GET, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=emby.mydomail.tld, X-Forwarded-Ssl=on, X-Forwarded-Uri=/videos/268691/master.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Original-Method=GET, X-Original-URL=https://emby.mydomail.tld:443/videos/268691/master.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Real-IP=host17
2024-12-17 15:12:45.915 Info Server: http/1.1 Response 200 to host2. Time: 1ms. GET http://host1:443/videos/268691/master.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit
2024-12-17 15:12:46.059 Info Server: http/1.1 GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit. Source Ip: host2, Accept=*/*, Connection=close, Host=host16, User-Agent=VLC/3.0.19 LibVLC/3.0.19, Accept-Encoding=deflate, gzip, Accept-Language=en_US, Cache-Control=no-cache, X-Forwarded-For=host17, X-Forwarded-Host=host1, X-Forwarded-Method=GET, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=emby.mydomail.tld, X-Forwarded-Ssl=on, X-Forwarded-Uri=/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Original-Method=GET, X-Original-URL=https://emby.mydomail.tld:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Real-IP=host17
2024-12-17 15:12:46.066 Info Server: http/1.1 Response 200 to host2. Time: 7ms. GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit
2024-12-17 15:12:48.100 Info Server: http/1.1 GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit. Source Ip: host2, Accept=*/*, Connection=close, Host=host16, User-Agent=VLC/3.0.19 LibVLC/3.0.19, Accept-Encoding=deflate, gzip, Accept-Language=en_US, Cache-Control=no-cache, X-Forwarded-For=host17, X-Forwarded-Host=host1, X-Forwarded-Method=GET, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=emby.mydomail.tld, X-Forwarded-Ssl=on, X-Forwarded-Uri=/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Original-Method=GET, X-Original-URL=https://emby.mydomail.tld:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Real-IP=host17
2024-12-17 15:12:48.106 Info Server: http/1.1 Response 200 to host2. Time: 6ms. GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit
2024-12-17 15:12:50.124 Info Server: http/1.1 GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit. Source Ip: host2, Accept=*/*, Connection=close, Host=host16, User-Agent=VLC/3.0.19 LibVLC/3.0.19, Accept-Encoding=deflate, gzip, Accept-Language=en_US, Cache-Control=no-cache, X-Forwarded-For=host17, X-Forwarded-Host=host1, X-Forwarded-Method=GET, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=emby.mydomail.tld, X-Forwarded-Ssl=on, X-Forwarded-Uri=/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Original-Method=GET, X-Original-URL=https://emby.mydomail.tld:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Real-IP=host17
2024-12-17 15:12:50.141 Info Server: http/1.1 Response 200 to host2. Time: 16ms. GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit
2024-12-17 15:12:52.227 Info Server: http/1.1 GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit. Source Ip: host2, Accept=*/*, Connection=close, Host=host16, User-Agent=VLC/3.0.19 LibVLC/3.0.19, Accept-Encoding=deflate, gzip, Accept-Language=en_US, Cache-Control=no-cache, X-Forwarded-For=host17, X-Forwarded-Host=host1, X-Forwarded-Method=GET, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=emby.mydomail.tld, X-Forwarded-Ssl=on, X-Forwarded-Uri=/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Original-Method=GET, X-Original-URL=https://emby.mydomail.tld:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=6d68ac6619fa46069f05643850f4258c&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit, X-Real-IP=host17
2024-12-17 15:12:52.241 Info Server: http/1.1 Response 200 to host2. Time: 13ms. GET http://host1:443/videos/268691/main.m3u8?DeviceId=eda7a206f008aef8&MediaSourceId=5e4701dff6de09be28a185883b55b830&PlaySessionId=1e1980d39f9c4149b2633091eb52cfb2&api_key=x_secret3_x&VideoCodec=h264&AudioCodec=aac&VideoBitrate=3360000&AudioBitrate=640000&AudioStreamIndex=1&TranscodingMaxAudioChannels=6&CopyTimestamps=true&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerBitrateExceedsLimit
```

**Comment by LukePulverenti** [comment]
Hi, can you get debugging info from yatse? I don't think the server log will be able to tell us what happened.

**Comment by godfuture** [comment]
Well, just a guess, but I think the issue is VLC not being able to play from Emby, because Yatse is not playing the media itself, just doing some kind of handover to VLC.

Are you asking for Yatse logs, because it might do false handover to VLC?

Update; playing from Emby Android app totally works.

**Comment by LukePulverenti** [comment]
The point is that the client is better equipped to debug this than the server. can you play inside yatse? can you play using vlc by itself with dlna?

**Comment by godfuture** [comment]
> The point is that the client is better equipped to debug this than the server. can you play inside yatse? can you play using vlc by itself with dlna?

Playing on native Yatse it looks a bit the same from client side:
```
2024-12-20 00:53:51.670 Verbose/EmbyLogger: <-- [235] Value cannot be null. (Parameter &#39;key&#39;)
2024-12-20 00:53:51.670 Verbose/EmbyLogger: <-- [235] END HTTP (8ms, 47-byte body)
2024-12-20 00:53:51.671 Error/EmbyLogger: Request Error: 400 [Value cannot be null. (Parameter &#39;key&#39;)]
```
I think the external media players dont provide logs or debug logs.

My assumption is a problem with subtitles. Maybe the call to Emby is done wrong such that loading subtitle breaks the whole request:
```
2024-12-20 00:54:04.332 Error App: Error getting subtitles
*** Error Report ***
Version: 4.8.10.0
Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 6.1.0-28-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT
Framework: .NET 6.0.31
OS/Process: x64/x64
Runtime: system/System.Private.CoreLib.dll
Processor count: 12
Data path: /config
Application path: /system
System.Threading.Tasks.TaskCanceledException: System.Threading.Tasks.TaskCanceledException: A task was canceled.
at Emby.ProcessRun.CoreProcess.CoreProcessLocal.WaitForExitAsync(CancellationToken cancellationToken)
at Emby.ProcessRun.Runners.ProcessRunnerBase.WaitForExitAsync(Int32 timeoutMs, CancellationToken cancellationToken)
at Emby.Server.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Boolean isAudio, String inputSubtitleCodec, MediaStream subtitleStream, SubtitleMediaTypes outputCodec, String outputPath, Nullable`1 startTime, Nullable`1 endTime, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
at Emby.Server.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(ReadOnlyMemory`1 inputPath, Boolean isAudio, String inputSubtitleCodec, MediaProtocol protocol, MediaStream subtitleStream, SubtitleMediaTypes outputCodec, String outputPath, Nullable`1 startTime, Nullable`1 endTime, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
at Emby.Server.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, MediaProtocol mediaSourceProtocol, Boolean isAudio, IDictionary`2 requestHeaders, MediaStream subtitleStream, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, EncodingContext encodingContext, CancellationToken cancellationToken)
at Emby.Server.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitles(String inputPath, MediaProtocol inputProtocol, Boolean isAudio, IDictionary`2 requestHeaders, MediaStream subtitleStream, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, EncodingContext encodingContext, CancellationToken cancellationToken)
at Emby.Api.Subtitles.SubtitleService.GetSubtitles(GetSubtitle request, CancellationToken cancellationToken)
at Emby.Api.Subtitles.SubtitleService.Any(GetSubtitle request)
Source: System.Private.CoreLib
TargetSite: Void ThrowForNonSuccess(System.Threading.Tasks.Task)
```
```
System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
```

**Comment by LukePulverenti** [comment]
Hi, have you reported the issue to the Yatse developer?

**Comment by LukePulverenti** [comment]
@godfuture ?

**Comment by godfuture** [comment]
> [@godfuture](https://github.com/godfuture) ?

Sorry for late reply. No, no yet. As I saw issues in emby server related to subtitle, and it worked before, I was quite convinced that this issue is located in server.

Is the stacktrace not indicating issues in server?

**Comment by LukePulverenti** [comment]
I only see small log snippets and no, they don't contain an obvious problem. The complete log file might reveal more.

**Comment by LukePulverenti** [comment]
@godfuture ?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to reopen with the requested information. Thanks.
